### ISSUE TITLE
gem unable to download data from https://rubygems.org/

### ISSUE THREAD

**Issue by monzou** [oneclick/rubyinstaller#161]
Hello.

I've installed Ruby Installer for Windows 1.9.3-p392 and try to install gem, then I got a following error.

```
$ gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A (https:
//rubygems.org/latest_specs.4.8.gz)
```

I don't know is this a problem of Ruby Installer or rubygems :confused: 
(gem 2.0.3 has a [similar issue](https://github.com/rubygems/rubygems/issues/515) on GItHub)

Do you have any ideas to solve this problem ?
My environments are following:
- Windows 7 (x64)
- Ruby Installer for Windows 1.9.3-p392
- gem 2.0.3

Regards,

**Comment by Caellian** [comment]
I have the same problem.
Here's everything I get from CMD:
[code]
F:\[X] SDK>gem install shoes --pre
ERROR:  Could not find a valid gem 'shoes' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

F:\[X] SDK>
[/code]

**Comment by Azolo** [comment]
That is actually a different issue altogether.

But [rubygems.org][1] was experiencing some problems. However, [It should be fixed now][2].

[1]: https://twitter.com/rubygems_status/status/619194799523004417
[2]: https://twitter.com/rubygems_status/status/619516810275221504

**Comment by Guihgo** [comment]
i just update gem... 
1- Download [ZIP] GEM from https://rubygems.org/pages/download#formats
2- open CMD as Administrator on folder extracted from ZIP
3- run: ruby setup.rb

4- be happy
