### ISSUE TITLE
ruby 187 on windows : Failed to build gem native extension (json)

### ISSUE THREAD

**Issue by melanie21** [oneclick/rubyinstaller#168]
Hi everybody, 

I'm trying to install redmine on my windows server 2008 R2. I downloaded and installed ruby on c:\Ruby187. After I created an directory called "Apps" and I typed the line "gem install rails" in c:\Ruby187\Apps. I obtained this error :

 "Fetching: json-1.7.7.gem (100%)
  ERROR:  Error installing rails:
  The 'json' native gem requires installed build tools.
  Please update your PATH to include build tools or download the DevKit
  from 'http://rubyinstaller.org/downloads' and follow the instructions
  at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'Fetching: json-1.7.7.gem (100%)"

So I downloaded the DevKit-tdm-32-4.5.2. I extracted it in c:\Rubt187\Devkit. After I run ruby dk.rb init and check that in the file config.yml was writted " - c:\Ruby187", I run ruby dk.rb install

When i gone in c:\Ruby187\Apps\ to run gem install rails

C:\Ruby187\Apps>gem install rails
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
 ERROR: Failed to build gem native extension.

c:/Ruby187/bin/ruby.exe extconf .rb
[.......]

Gem files will remain installed in C:/Ruby187/lib/ruby/gems/1.8/gems/json-1.7.7 for inspection.
Results logged to C:/Ruby187/lib/ruby/gems/1.8/gems/json-1.7.7/ext/json/ext/generator/gem_make.out

Someone can help me please, I dont know what can I do ....

**Comment by balmyBanzai** [comment]
@luislavena 's last comment is what ended up unblocking me. Thanks for all the feedback!

**Comment by shashiponnam** [comment]
Installing Json 1.8.6 gem worked after executing "ruby dk.rb install -f ". Thanks much luislavena
