### ISSUE TITLE
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:125:14: error: size of array 'ruby_check_sizeof_voidp'  is negative

### ISSUE THREAD

**Issue by ghost** [oneclick/rubyinstaller#175]
1. Follow installation instructions
   - Install rubyinstaller-2.0.0-p195.exe
   - Extract DevKit to C:\DevKit; cmd; cd into dir; ruby dk.rb init; and ruby dk.rb install
   - no errors
2. Attempt to gem install json --platform=ruby
   - Utter painful catastrophic failure
- Win7 64 Pro
- DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe
- rubyinstaller-2.0.0-p195.exe

```
$ gem install json --platform=ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    c:/Ruby200/bin/ruby.exe extconf.rb
creating Makefile

make
generating generator-i386-mingw32.def
compiling generator.c
In file included from c:/Ruby200/include/ruby-2.0.0/ruby.h:33:0,
                 from ../fbuffer/fbuffer.h:5,
                 from generator.c:1:
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:125:14: error: size of array 'ruby_check_sizeof_voidp'
 is negative
In file included from c:/Ruby200/include/ruby-2.0.0/ruby.h:33:0,
                 from ../fbuffer/fbuffer.h:5,
                 from generator.c:1:
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h: In function 'rb_float_value':
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:826:13: warning: cast to pointer from integer of diffe
rent size [-Wint-to-pointer-cast]
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h: In function 'rb_num2char_inline':
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1214:35: warning: cast to pointer from integer of diff
erent size [-Wint-to-pointer-cast]
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1214:35: warning: cast to pointer from integer of diff
erent size [-Wint-to-pointer-cast]
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1214:35: warning: cast to pointer from integer of diff
erent size [-Wint-to-pointer-cast]
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1215:9: warning: cast to pointer from integer of diffe
rent size [-Wint-to-pointer-cast]
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1215:9: warning: cast to pointer from integer of diffe
rent size [-Wint-to-pointer-cast]
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1215:9: warning: cast to pointer from integer of diffe
rent size [-Wint-to-pointer-cast]
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h: In function 'rb_class_of':
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1514:12: warning: cast to pointer from integer of diff
erent size [-Wint-to-pointer-cast]
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h: In function 'rb_type':
c:/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1531:12: warning: cast to pointer from integer of diff
erent size [-Wint-to-pointer-cast]
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function 'fbuffer_append_str':
```

**Comment by DouglasAllen** [comment]
ruby 2.0.0p648 (2015-12-16) [i386-mingw32]

DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe

And still the same.

In file included from c:/row/Ruby200/include/ruby-2.0.0/ruby.h:33:0,
                 from ../../../../ext/calc_sun/calc_sun.c:1:
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:125:14: error: size of array 'ruby_check_sizeof_voidp' is negative
In file included from c:/row/Ruby200/include/ruby-2.0.0/ruby.h:33:0,
                 from ../../../../ext/calc_sun/calc_sun.c:1:
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h: In function 'rb_float_value':
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:826:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h: In function 'rb_num2char_inline':
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1214:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1214:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1214:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1215:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1215:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1215:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h: In function 'rb_class_of':
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1515:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h: In function 'rb_type':
c:/row/Ruby200/include/ruby-2.0.0/ruby/ruby.h:1532:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
make: *** [calc_sun.o] Error 1
rake aborted!
Command failed with status (2): [C:\devkit\\bin/make.exe...]
