### ISSUE TITLE
ruby 1.9.3p545 miss Fiddle.dlopen method

### ISSUE THREAD

**Issue by net1957** [oneclick/rubyinstaller#223]
fail on 1.9.3 but is ok on 2.0.0 (windows 8.1 x64)

ruby 1.9.3p545 (2014-02-24) [i386-mingw32]

```
irb(main):001:0> require 'fiddle'
=> false
irb(main):002:0> version_dll = Fiddle.dlopen('version.dll')
NoMethodError: undefined method `dlopen' for Fiddle:Module
        from (irb):2
        from D:/program/dvlt/ruby/ruby193/bin/irb:12:in `<main>'
irb(main):003:0>
```

ruby 2.0.0p481 (2014-05-08) [x64-mingw32]

```
irb(main):001:0> require 'fiddle'
=> false
irb(main):002:0> version_dll = Fiddle.dlopen('version.dll')
=> #<Fiddle::Handle:0x00000002b31760>
irb(main):003:0> exit
```

seems to be related to https://github.com/luislavena/rb-readline/issues/98

**Comment by saikrishnagaddipati** [comment]
I am having same issue? 
Was this issue resolved? Can anyone  help me showing the right path for the above issue?

**Comment by saikrishnagaddipati** [comment]
@luislavena @lamont-granquist @net1957

**Comment by luislavena** [comment]
@saikrishnagaddipati please see previous comments which contains answers. There is no `Fiddle.dlopen` in 1.9.3 and there will be not. For 1.9.3: use `DL`, for 2.0.0 or newer, use `Fiddle.dlopen`

**Comment by lamont-granquist** [comment]
1.9.3 is no longer supported, stop using it and use Fiddle.dlopen.
