### ISSUE TITLE
Any plans to support Mingw64-64 4.9.1

### ISSUE THREAD

**Issue by wkwood** [oneclick/rubyinstaller#232]
Any official plans to support Mingw64-64 4.9.1?  Right now 4.7.2 is a bit stale and I hit a -O3 optimization bug recently with it.  FYI Here's my recent changes to mingw64.rb.  I'm getting a stable build with it.

COMPILERS['mingw64-64-4.9.1'] =
    OpenStruct.new(
      :version => 'mingw64-64-4.9.1',
      :programs => [ :gcc, :cpp, :'g++' ],
      :program_prefix => nil,
      :url_1 => 'http://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.1/threads-win32/seh',
      :url_2 => 'http://downloads.sourceforge.net/mingw',
      :url_3 => 'http://downloads.sourceforge.net/gnuwin32',
      :target => 'sandbox/devkit/mingw',
      :relocate => 'sandbox/devkit/mingw/mingw64',
      :host => 'x86_64-w64-mingw32',
      :files => {
        :url_1 => [
          'x86_64-4.9.1-release-win32-seh-rt_v3-rev0.7z',
         ],
        :url_2 => [
          'autoconf2.1-2.13-4-mingw32-bin.tar.lzma',
          'autoconf2.5-2.68-1-mingw32-bin.tar.lzma',
          'autoconf-10-1-mingw32-bin.tar.lzma',
          'automake1.11-1.11.1-1-mingw32-bin.tar.lzma',
          'automake-4-1-mingw32-bin.tar.lzma',
          'libexpat-2.0.1-1-mingw32-dll-1.tar.gz',
          'libtool-2.4-1-mingw32-bin.tar.lzma',
          'bsdtar-2.8.3-1-mingw32-bin.tar.bz2',
          'bsdcpio-2.8.3-1-mingw32-bin.tar.bz2',
          'libarchive-2.8.3-1-mingw32-dll-2.tar.bz2',
          'libbz2-1.0.5-2-mingw32-dll-2.tar.gz',
          'liblzma-4.999.9beta_20100401-1-mingw32-dll-1.tar.bz2',
          'libz-1.2.3-1-mingw32-dll-1.tar.gz'
        ],
        :url_3 => [
          'which-2.20-bin.zip'
        ],
      }
    )

**Comment by sodabrew** [comment]
Could I bump this thread? I found that the MinGW in present versions of DevKit are not providing some newer (read: available since Windows XP...) getaddrinfo constants:
https://github.com/eventmachine/eventmachine/pull/659

These were added to MinGW somewhat recently: http://sourceforge.net/p/mingw-w64/mailman/message/33056995/

**Comment by luislavena** [comment]
@sodabrew see the implications here: #297

**Comment by larskanis** [comment]
This is resolved in https://github.com/oneclick/rubyinstaller2 .
