### ISSUE TITLE
Missing _gmtime64_s in library msvcrt.dll

### ISSUE THREAD

**Issue by elmersaid** [oneclick/rubyinstaller#239]
_gmtime64_s not found in library dynamic linked msvcrt.dll

can you make you next version resolve this problem !!
you can put this function in your msvcrt-ruby210.dll and load it from this file not from windows dll
its just in this version when i try older version no problem but can't downloads some gem !!

**Comment by MarkDBlackwell** [comment]
See #271 for a solution.
