### ISSUE TITLE
 `rename': Permission denied @ sys_fail2

### ISSUE THREAD

**Issue by RomanADavis** [oneclick/rubyinstaller#246]
Searched the issues. Didn't find anything. Followed the instructions, here's what happens.

PS C:\Users\Roman> ruby dk.rb init
[INFO] found RubyInstaller v1.9.3 at C:/Program Files (x86)/Heroku/ruby-1.9.3
[INFO] found RubyInstaller v2.1.3 at C:/Ruby21

Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit.
PS C:\Users\Roman> ruby dk.rb install
[INFO] Updating convenience notice gem override for 'C:/Program Files (x86)/Heroku/ruby-1.9.3'
dk.rb:86:in `rename': Permission denied @ sys_fail2 - (C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1
/rubygems/defaults/operating_system.rb, C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/defau
lts/operating_system.rb.20141106064922) (Errno::EACCES)
        from dk.rb:86:in`update_gem_override'
        from dk.rb:260:in `block (2 levels) in install'
        from dk.rb:246:in`each'
        from dk.rb:246:in `block in install'
        from dk.rb:219:in`each'
        from dk.rb:219:in `install'
        from dk.rb:313:in`run'
        from dk.rb:332:in `<main>'

**Comment by andrew-linck** [comment]
make sure the file is closed when you try to rename it. So mine was
`file = File.open("sample.txt, "r")`
`file.close`

Then I could rename it
`file.rename("sample.txt", "rename_sample.txt")`
