### ISSUE TITLE
add mysql2 gem for windows 

### ISSUE THREAD

**Issue by moody404** [oneclick/rubyinstaller#247]
Dears 

I am very thankful for your amazing effort to make rubyinstaller possible by just couple clicks . 

we  would love if you could support MySQL by default as it not easy to install it in windows 

if you make quick search you will find many are stuck in this step  , me included as i tried many possible solutions and worked with me once and failed many . I think it is very critical for beginners to install MySQL , especially the one who would only focus on learning ruby and rails without worrying about how to install this or that ,Just like using ruby-installer  

it would be extremely amazing if Ruby-installer come with per-configured MySQL gem or at least make it easier to do "gem install mysql2" as it with most ruby gems 

Thank you

**Comment by Azolo** [comment]
While I understand your frustration, this isn't really a goal of RubyInstaller.

Likewise in this case it is really up to the gem provider to provide "fat binaries" for gems in which they compile the gem themselves and release it. Which the maintainer may or may not do and in some cases simply cannot.

In the case of this particular gem, it looks like @luislavena [did some awesome work with the current maintainers][1] and it will have fat binaries next release.

[1]: https://github.com/brianmario/mysql2/pull/473

**Comment by sodabrew** [comment]
At the moment, if you have a mingw compiler available, the best option in your Gemfile is:

gem 'mysql2', github: 'brianmario/mysql2', ref: '72dedddac9de02b50d44ef0fbea6a99aedac486c'

I will build fat binaries for the next release in the coming months.

**Comment by sodabrew** [comment]
I released mysql2 version 0.3.18 **with windows binaries** today! Please give it a spin, report any issues to https://github.com/brianmario/mysql2.
