### ISSUE TITLE
Disallow installation to paths with a " " (space) in them.

### ISSUE THREAD

**Issue by dweremeichik** [oneclick/rubyinstaller#248]
It appears that the installer allows you to install to a location with a " " (space) in the file name. However if you do this, it can cause issues related to running ruby gems. Key example: Foundation (http://foundation.zurb.com/docs/sass.html)  If you try to run the foundation gem, (foundation new MY_PROJECT) with ruby installed to "C:\Program Files\RubyXXXX" it will break at "C:\Program" when trying to execute the gem.

**Comment by collinsauve** [comment]
A bug should be reported for the gem.  The correct path for program files on Windows is `C:\Program Files`.  You're not going to change that.

The fact that this defaults to installing to a folder directly under `C:\` should actually be considered a bug in this installer.  This is as if something installing on Ubuntu wanted to install to `/ruby24-x64`.  Respect the proper install locations for each OS!

**Comment by dweremeichik** [comment]
Fair enough. It's been a long time since I have used that gem, or looked at this issue.
