### ISSUE TITLE
Change OpenSSL certificates path

### ISSUE THREAD

**Issue by mpapis** [oneclick/rubyinstaller#249]
Forwarding http://stackoverflow.com/questions/19150017/ssl-error-when-installing-rubygems-unable-to-pull-data-from-https-rubygems-o/19151697?noredirect=1#comment38117738_19151697

The path to OpenSSL certificates can be configured with: `--openssldir=` ([Example](https://github.com/sm/sm-libraries/blob/master/openssl/shell/functions#L19))

I have seen few issues about this in here, but none proposed to change the path to something that would not confuse users, I also know that Windows is not as flexible as Linux/OSX with paths, maybe `C:/Users/etc/openssl/`? although not all users have `C:` :(

**Comment by johnrc** [comment]
@luislavena Thanks for the link and fix. When do you expect the next Ruby installer to be available with the updated RubyGems that fixes the ssl issue?

**Comment by gwaldo** [comment]
This is fantastic.

**Comment by schneems** [comment]
Thanks for all the work here, ran into this while trying to update some documentation on a windows VM. Any idea when a version of RailsInstaller with these fixes will be able to go out?

**Comment by Azolo** [comment]
The next RubyInstaller package with these fixes should be released with the next official Ruby 2.2.X release.

**Comment by Azolo** [comment]
All current and supported versions of RubyInstaller have new releases that solve this rubygems issue.

Most current releases are 2.0.0-p645, 2.1.6, 2.2.2.

And thus the RubyInstaller saga of the dreaded **Rubygems.org Certificate Update** begins its closing act.

**Comment by schneems** [comment]
OMG, thank you so much :heart: :heart: :heart:

**Comment by pbennett** [comment]
p.s. I just downloaded 2.2.5 32-bit and it still has this problem. :(
I had to remove the https source, add the http source, and update the rubygems version.

**Comment by mwaldz** [comment]
@pbennett , how did You remove the https source?
Thank You in advance!

**Comment by pbennett** [comment]
@mwaldz
gem source -r https://rubygems.org/
gem source -a http://rubygems.org/
gem update --system
gem source -r http://rubygems.org/
gem source -a https://rubygems.org/

**Comment by ajithsimon** [comment]
It works well.. Thanks a lot.

**Comment by mwaldz** [comment]
Thank You!

**Comment by cj13579** [comment]
Thanks @pbennett !!

**Comment by luzusomuch** [comment]
Thank you.

**Comment by hilaolu** [comment]
@pbennett It works!!! thx

**Comment by jono-frazer** [comment]
Elegant and simple.  Seems to have worked for me.  Much appreciated.

**Comment by alilland** [comment]
> @[pbennett](https://github.com/pbennett)
gem source -r https://rubygems.org/ 
gem source -a http://rubygems.org/ 
gem update --system 
gem source -r http://rubygems.org/ 
gem source -a https://rubygems.org/

attempted all steps, but at `gem update --system` I get the following error
```
PS C:\Users\ALilland> gem update --system
Updating rubygems-update
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/api/v1/dependencies)
```

**Comment by MSP-Greg** [comment]
@alilland 

What version of Ruby (`ruby -v`) are you using?

**Comment by alilland** [comment]
@MSP-Greg  2.3.3 

unfortunately i'm bound to it for the time being

**Comment by MSP-Greg** [comment]
Ok.  No comment.

1. Download either of the following (these are show at https://github.com/ruby/setup-ruby/blob/master/windows-versions.json):

   https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-head/rubyinstaller-head-x64.7z or
   or
   https://github.com/MSP-Greg/ruby-loco/releases/download/ruby-master/ruby-ucrt.7z

2. Unzip them somewhere.

3.  Within them, either at 'etc/ssl' or 'ssl', you'll find a file named `cert.pem`.  You will need its full path.  This is a very current cert file, which your Ruby install is lacking.

4. Set `ENV['SSL_CERT_FILE']` to  `cert.pem`'s path (PowerShell `$env:SSL_CERT_FILE = "\<path to file\>".  This allows you to change the cert location, since it's probably missing with Ruby 2.3.

5. Run `gem update --system 3.3.26` for the most recent RubyGems compatible with Ruby 2.3.  It also includes bundler.

I rarely use Ruby 2.3, but I have it installed.  Ran the above, and it all worked.  Even installed a gem...

**Comment by MSP-Greg** [comment]
Re the cert file (`cert.pem`), Ruby's default location for it can be found with:
```
ruby -ropenssl -e "puts OpenSSL::X509::DEFAULT_CERT_FILE"
```
If you want to create that path on your system and place the `cert.pem` file in it, you won't need to set `ENV['SSL_CERT_FILE']`

Obviously, the version of OpenSSL bundled with Ruby 2.3 (OpenSSL 1.0.2j  26 Sep 2016) is old and considered insecure.  There are probably at least a few security related bugs in Ruby 2.3 and the other EOL Ruby versions.  Just thought I'd make that clear...

**Comment by dmajkic** [comment]
You could disable ssl check. Create file

   c:\Users\yourusername\.gemrc
   
 add  
 
   :ssl_verify_mode: 0
