### ISSUE TITLE
Problem with MySQL and gem

### ISSUE THREAD

**Issue by MSalehi** [oneclick/rubyinstaller#253]
Trying to install SASS with rubyinstaller and this error happened :
![untitled](https://cloud.githubusercontent.com/assets/5165298/5670597/b0a6f6de-9796-11e4-9ed3-61fd75a3770e.png)
I'm using Windows 7 x64
and i have XAMPP Package on my computer
i tried to stop the mysql service but problem has not resolve.

**Comment by Azolo** [comment]
This looks like this is a rubygems issue with the native Arabic code page.
The MySQL error looks unrelated to the problem.

Try changing your [code page][1] to UTF-8 (which is 65001).

    > chcp 65001
    > gem install sass

If that doesn't work let me know and I'll look into it some more.

[1]: http://en.wikipedia.org/wiki/Code_page

**Comment by MSalehi** [comment]
Thanks!
i tried this, but another error happened :(
![untitled](https://cloud.githubusercontent.com/assets/5165298/5876153/f900d05a-a329-11e4-8fcb-a3b8801fece7.png)
