### ISSUE TITLE
error message testing devkit installation

### ISSUE THREAD

**Issue by wwen0** [oneclick/rubyinstaller#257]
I think I have devkit installed successfully. But when I tried to test the installation using "gem install json --platform=ruby", all I got was the following error message:

ERROR:  Could not find a valid gem 'json' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)

Anyone who can tell me how to solve this problem is greatly appreciated. Thanks

**Comment by Azolo** [comment]
Please Take a look at:

https://gist.github.com/luislavena/f064211759ee0f806c88
