### ISSUE TITLE
Cannot delete installation icon

### ISSUE THREAD

**Issue by mangulo1207** [oneclick/rubyinstaller#258]
I don't want to say this but I am going to say it. To me, this is a virus. I cannot delete the rubyinstaller -2.1.5 from my windows PC. I try to rename the file and my computer crashes every time. Thanks for wasting my time.

**Comment by Azolo** [comment]
Honestly, I'm sorry. It seems like something really frustrating is happening. But RubyInstaller can't act in that way. It doesn't even require Administrator access to install and doesn't make sweeping changes to the file system.

My best guess is that you have some corrupt/bad sectors on your hard drive. Have you tried [checking your hard drive for errors(Windows 7)][1]?

If by some chance this ends up being a problem with the installer then I will look into it and fix it. With the information you gave though it just sounds like a shitty coincidence.

[1]:http://windows.microsoft.com/en-us/windows7/Check-a-drive-for-errors
