### ISSUE TITLE
Resources not included in 2.2.0 ruby.exe and rubyw.exe files

### ISSUE THREAD

**Issue by clpo13** [oneclick/rubyinstaller#260]
I built Ruby 2.2.0 with DevKit mingw64-64-4.7.2 (Windows 7 x64) and everything compiled just fine. However, the ruby.exe and rubyw.exe files don't have their respective icons embedded. I built 2.1.5 and those files had icons. The icons and *.rc files are present in the build directory.
![ruby21](https://cloud.githubusercontent.com/assets/442365/6262779/1380e740-b7bf-11e4-94b9-8926e2970d80.PNG)
![ruby22](https://cloud.githubusercontent.com/assets/442365/6262781/16edd94c-b7bf-11e4-80db-76598a3a220a.PNG)

**Comment by Azolo** [comment]
There is a problem building one of the standard libraries in Ruby 2.2. As a result the build process never finishes and things like this aren't completed.

See #254 for more info.
