### ISSUE TITLE
update to Gems 2.2.3 to avoid SSL workaround on Windows

### ISSUE THREAD

**Issue by shanselman** [oneclick/rubyinstaller#261]
Folks are still having to do this work around from last year: https://gist.github.com/luislavena/f064211759ee0f806c88

So when I setup machines I have to:

    curl -L o update.gem https://github.com/rubygems/rubygems/releases/download/v2.2.3/rubygems-update-2.2.3.gem
    call gem install --local update.gem
    update_rubygems --no-ri --no-rdoc
    call gem uninstall rubygems-update -x

Will the next release have gem 2.2.3?

**Comment by Azolo** [comment]
Yeah, it will. There was a problem with the building part of the stdlib in the Ruby 2.2 release when building with mingw, so we didn't actually get a release out. 

But Ruby 2.2.1 and any maintenance release of previous versions should have an updated rubygems. I certainly hope it does.

I just have no idea when then next release will be.

**Comment by shanselman** [comment]
Thanks for your work! We who are using Ruby on Windows truly appreciate it!

**Comment by Azolo** [comment]
So I was preparing the 2.0.0p643 release and it doesn't have an updated version of rubygems.

Snooping around some more, [a fix was applied to the `ruby_2_2` branch][1] and then [backported to the `ruby_2_1` branch][2].

However the [`ruby_2_0_0` branch][3] did not get the rubygems backported.

Gonna wait till a release to close this ticket though.

[1]: https://github.com/ruby/ruby/commit/97f80207d0f0d13f28a419d8c92e96bb9064096a
[2]: https://github.com/ruby/ruby/commit/d532ce90d9a9ed74295e249f10cda58595deeed4
[3]: https://github.com/ruby/ruby/blob/ruby_2_0_0/lib/rubygems.rb

**Comment by Azolo** [comment]
Ok, [RubyInstaller 2.1.6 has been uploaded and released][1].

Shouldn't have to do the SSL cert workaround anymore now.

[1]: https://bintray.com/oneclick/rubyinstaller/rubyinstaller/2.1.6

**Comment by shanselman** [comment]
Yaaay! Thanks!

On Thu, Apr 16, 2015 at 12:49 PM, Justin Baker <notifications@github.com>
wrote:

> Ok, RubyInstaller 2.1.6 has been uploaded and released
> <https://bintray.com/oneclick/rubyinstaller/rubyinstaller/2.1.6>.
>
> Shouldn't have to do the SSL cert workaround anymore now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oneclick/rubyinstaller/issues/261#issuecomment-93824950>
> .
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes
