### ISSUE TITLE
Support channel for latest build of Ruby 2.2.1

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller#262]
Hi all,

I'm just wonder is there any channel of RubyInstaller support for the latest release of Ruby, e.g, at the moment the current version is 2.2.1. I found that the ruby in rubyinstaller website is 2.1.x.

Thanks!

**Comment by Azolo** [comment]
It usually takes RubyInstaller a couple of days to release a new version. But we try to do it as soon as possible.

Ruby 2.2.1 was released last night, so stayed tuned for a release in the next couple of days.

If you are really itching for the release you can compile your own using the RubyInstaller repo.

**Comment by Azolo** [comment]
RubyInstaller 2.2.1 has been released.

Checkout the BinTray page for downloads:
https://bintray.com/oneclick/rubyinstaller/rubyinstaller/2.2.1/view

**Comment by duytrung** [comment]
Thanks so much Azolo. Basically I don't have MSVC++ compiler installed and don't know much about the compiling process. 

Regards

**Comment by Azolo** [comment]
We don't use MSVC++, we use mingw because we can distribute it freely.

The DevKit is the entire tool chain and the RubyInstaller project will actually bootstrap it for you.

Just running `rake ruby22 DKVER=mingw64-32-4.7.2` will take you start to finish with no extra software besides Ruby and Git.
