### ISSUE TITLE
Unable to download data from https://rubygems.org/

### ISSUE THREAD

**Issue by ryanburnett** [oneclick/rubyinstaller#263]
Just installed Ruby 2.1.5 (x64) on Windows 7. Opened "Start Command Prompt with Ruby" and ran:

`gem install sass`

...and got this error:

```
ERROR:  Could not find a valid gem 'sass' (>= 0), here is why:
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

Any idea how I can install Sass?

**Comment by Azolo** [comment]
See #249 for more info

For a fix see:
https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by gokulrajan** [comment]
For Quick Fix, in Gemfile, replace "source 'https://rubygems.org'" to "source 'http://rubygems.org'"
