### ISSUE TITLE
ruby installer link is broken

### ISSUE THREAD

**Issue by kevanous** [oneclick/rubyinstaller#265]
All the ruby installer links are not working currently

**Comment by Azolo** [comment]
I'm guessing your location is in Europe? In which case the European Bintray cdn server is messed up. Bintray said their DNS is pointing the to the US server though.

More Info:  
https://twitter.com/bintray/status/585525572798918658
https://twitter.com/bintray/status/585525917998514177

**Comment by Azolo** [comment]
Also as a note, it looks like server stability has been a problem the past few days. See #264
