### ISSUE TITLE
I believe 2.2.2 Ruby is released already

### ISSUE THREAD

**Issue by lmayorga1980** [oneclick/rubyinstaller#266]
Any tentative date for the windows one?

**Comment by Azolo** [comment]
It takes a couple of days to get a release out. I'll get it done as soon as possible.

See #262 for more details

**Comment by duytrung** [comment]
Bravo! I'm eager to download this version from rubyinstaller website! Thanks to rubyinstaller! :100:

**Comment by Azolo** [comment]
Alright, RubyInstaller 2.2.2 is released and uploaded.

I still recommend 2.1.6 over 2.2.2 because it's still not possible to cross-compile gems for Ruby 2.2.
With the release of Ruby 2.2.2 it will be fixed soon.

For more info see: tjschuck/rake-compiler-dev-box#20

**Comment by lmayorga1980** [comment]
I believe the MSI Installer is not available yet http://rubyinstaller.org/downloads/

**Comment by Azolo** [comment]
I don't know why but maybe your page hasn't updated yet?

Anyway, you can also get the package from Bintray:
https://bintray.com/oneclick/rubyinstaller/rubyinstaller/2.2.2

Direct Links:
**32-bit:** http://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.2.1.exe
**64-bit:** http://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.2.1-x64.exe
