### ISSUE TITLE
RubyInstaller seems to install openssl 1.0.1l but Ruby claims it is using 1.0.0h

### ISSUE THREAD

**Issue by ldanielw1** [oneclick/rubyinstaller#270]
Hi,

I ran a simple "rake ruby19 TRUNK=1". In sandbox/openssl/bin, I'm seeing openssl.exe that return "OpenSSL 1.0.1l" when I run "openssl version".

However, when I start sandbox/ruby19_build/bin/irb and then enter "OpenSSL::OPENSSL_VERSION", I get "1.0.0h". Is there some constant that isn't getting properly updated? Is 1.0.1l not being properly installed?

**Comment by ldanielw1** [comment]
And running the irb from ruby19_mingw/bin/irb, that one's OpenSSL::OPENSSL_VERSION is "OpenSSL 1.0.1" - which also isn't 1.0.1l. Not sure what's going on, and how these two are pulling in 1.0.0h and 1.0.1 when the only openssl downloaded through rubyinstaller is 1.0.1l...?

**Comment by Azolo** [comment]
Right, so I honestly don't know.
I know that `OPENSSL_VERSION` is compile time hard coded, but it seems like you may be getting some versions from somewhere else.

You may run `rake clobber` before you compile again, *just in case*, but I doubt that's the problem.

I'll look into it some more when I get some time.

**Comment by sroller** [comment]
From what I can see Ruby uses the DLL/shared libray in
c:/ruby/lib/ruby/2.1.0/x64-mingw32/openssl.so

I'm currently running Ruby 2.1.6 on that machine.
If you type openssl on the command line - I understand at least that's what
you did - then you call some openssl.exe somewhere on your machine which
has nothing to do with aforementioned Ruby lib.

Try

which openssl

to find out where your command is located. On my machine there is one
version which come with git and that's even version 0.9.8zb from 6-AUG-2014.



2015-04-20 22:17 GMT-04:00 Justin Baker <notifications@github.com>:

**Comment by ldanielw1** [comment]
You're right - so I do have one ruby installed at C:\Ruby193-p194, which has an openssl configured at OpenSSL 1.0.0h. However, don't I need ruby installed to run rubyinstaller? Feels a bit circular, unless I need to replace the DLLs in my installed version of Ruby prior to running this Ruby, as well?

**Comment by ldanielw1** [comment]
Alright - that turned out to be a horrible idea because replacing my two DLLs now makes it impossible for me to run:
require "openssl"

any other suggestions?

**Comment by Azolo** [comment]
So, I just did a build of Ruby 1.9.3 using `rake ruby19` and it looks like it compiled with new OpenSSL.

    PS ...\rubyinstaller\sandbox\ruby19_mingw> .\bin\ruby.exe -ropenssl -e "puts OpenSSL::OPENSSL_VERSION"
    OpenSSL 1.0.1l 15 Jan 2015

But, it looks like the current recipes don't work with Ruby 1.9.3's `irb` (because of rbreadline).

I dropped the mingw64 versions into an existing Ruby 1.9.3 and it seemed to be able to `require 'openssl'`.

I'm going to try a previous version of rbreadline and compile again so `irb` should work

**Comment by Azolo** [comment]
Ok, to get a working version you'll have to change the `rbreadline` version to `v0.5.0`. [This is the diff](https://gist.github.com/Azolo/390a11731cec37f8902f)

Then see if you get:

    PS ...\rubyinstaller> cd .\sandbox\ruby19_mingw
    ...\rubyinstaller\sandbox\ruby19_mingw
    PS ...\rubyinstaller\sandbox\ruby19_mingw> .\bin\ruby.exe .\bin\irb
    irb(main):001:0> require 'openssl'
    => true
    irb(main):002:0> OpenSSL::OPENSSL_VERSION
    => "OpenSSL 1.0.1l 15 Jan 2015"

If you do then run `rake ruby19:package:archive` to get a 7z archive.

**Comment by ldanielw1** [comment]
@Azolo Thanks so much - things are looking good now!

**Comment by Azolo** [comment]
No Problem. Good Luck!
