### ISSUE TITLE
Building OpenSSL myself so that Ruby can have latest version of OpenSSL?

### ISSUE THREAD

**Issue by ldanielw1** [oneclick/rubyinstaller#272]
I have a pre-built version of OpenSSL 1.0.1m, and I would like to get it to build with rubyinstaller. I have no problems with uploading it here or something so that RubyInstaller can pull it down during installation process. But is there anything I need to know about how OpenSSL needs to be compiled, how I ought to be arranging produced files it into the nice tarred up format that I'm seeing on Bintray?

**Comment by Azolo** [comment]
It's actually really easy to upload things to a personal repository on [Bintray][1] if you would like.

If you add recipe to [knapsack-recipes][2] and I will build it then I will build it locally and upload the binaries to the [OpenKnapsack repo on Bintray][3]. For an example see: oneclick/knapsack-recipes#8

As for the format, it's from [knap-build][4]. I use this command:

    C:\...\knap-build> .\bin\knap-build.bat openssl -v 1.0.1l --package

As for how to use locally build versions @jonforums has a nice quick little hack to do so. He posted a reference to it in #254 in [this comment][5].

[1]: https://bintray.com/
[2]: https://github.com/oneclick/knapsack-recipes
[3]: https://bintray.com/oneclick/OpenKnapsack
[4]: https://github.com/oneclick/knap-build
[5]: https://github.com/oneclick/rubyinstaller/issues/254#issuecomment-86532401
