### ISSUE TITLE
Building Ruby with my own custom version of openssl?

### ISSUE THREAD

**Issue by ldanielw1** [oneclick/rubyinstaller#275]
I previously submitted a post about building ruby with the latest versions of openssl, but since then, I have created my own custom version of openssl with my own changes. I have gotten it to build, but I don't know how to get rubyinstaller to pull that in properly. Can somebody point me in the right direction with how to do that? I saw a post by @jonforums in another thread about creating an override/openssl.rb file, but that seems to still point at OpenKnapsack.

Is there any way for me to copy in certain files during the build process for ruby to pick up my own version of openssl?

**Comment by jonforums** [comment]
I have a `override/openssl.rb` file containing

~~~ ruby
if ENV['OPENSSL']
  ssl_version = ENV['OPENSSL']
  puts "---> Using OpenSSL #{ssl_version}"

  RubyInstaller::KNAPSACK_PACKAGES['openssl'].version = ssl_version
  RubyInstaller::KNAPSACK_PACKAGES['openssl'].files = [ "openssl-#{ssl_version}-x86-windows-bin.7z" ]
end
~~~

After I place my custom built `openssl-1.0.2c-x86-windows-bin.7z` lib archive in `downloads`, I build ruby similar to the following. The build process picks up the new version of OpenSSL and build/tests OK for me on Win8.1 x64 doing 32-bit builds (I don't use ruby for any 64-bit dev).

~~~ shell
rake ruby21 local=C:\Users\Jon\Documents\RubyDev\ruby-git openssl=1.0.2c dkver=mingw64-32-4.9.2
~~~

Spelunk files in the `config` dir if you want to try using newer versions of libs.

**Comment by ldanielw1** [comment]
oh i see. How did you get this custom built 1.0.2c? when I build my openssl, I just get a bunch of binaries, like ssleay32.dll and libeay32.dll...

**Comment by jonforums** [comment]
I built an alpha quality toolkit for automating the builds of a number of native libs that I use https://github.com/jonforums/buildlets

If you look at my OpenSSL build recipe

https://github.com/jonforums/buildlets/blob/master/build_openssl.ps1#L47-L71

you'll see there is not a logic of magic I do above and beyond the normal OpenSSL build steps. I'm guessing all you need to do with your custom build is:

1. archive all your OpenSSL artifacts into a .7z or .zip containing bin/, include/, lib/ subdirs (crack open an older Knapsack built OpenSSL archive to see the layout). Likely running OpenSSL's `make install_sw` will give you the correct dir structure you can then archive.
2. put your archive in `downloads`
3. create an appropriate override file
4. build and test

While I use my build recipes and am OK with the current sharp edges, for RubyInstaller I'd highly suggest working with @Azolo on updating/testing the OpenSSL Knapsack build recipe.

**Comment by jack71** [comment]
:+1:

**Comment by Azolo** [comment]
@ldanielw1 I'm going to go ahead and close this, since it isn't exactly a bug and there is a way to do it.

If you're having problems you can continue to use this report for discussion, I am more than happy to help out.

**Comment by roy128** [comment]
:+1:
