### ISSUE TITLE
Can't compile native gems although installing them works

### ISSUE THREAD

**Issue by Maher4Ever** [oneclick/rubyinstaller#276]
Hello there,

I'm trying to compile [WDM](https://github.com/Maher4Ever/wdm) on a Windows 7 64-bit machine running ruby 2.2.2p95 32-bit with devkit installed of course. I keep getting the same error:

```
C:/Ruby22/bin/ruby.exe -I. ../../../../ext/wdm/extconf.rb
checking for main() in -lkernel32... *** ../../../../ext/wdm/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=../../../../ext/wdm
        --curdir
        --ruby=C:/Ruby22/bin/$(RUBY_BASE_NAME)
        --with-kernel32lib
        --without-kernel32lib
C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
        from ../../../../ext/wdm/extconf.rb:19:in `<main>'
rake aborted!
Command failed with status (1): [C:/Ruby22/bin/ruby.exe -I. ../../../../ext...]

Tasks: TOP => compile => compile:i386-mingw32 => compile:wdm_ext:i386-mingw32 => copy:wdm_ext:i386-mingw32:2.2.2 => tmp/i386-mingw32/wdm_ext/2.2.2/wdm_ext.so => tmp/i386-mingw32/wdm_ext/2.2.2/Makefile
```

The `mkmf.log` file contains the following:

```
"gcc -o conftest.exe -IC:/Ruby22/include/ruby-2.2.0/i386-mingw32 -IC:/Ruby22/include/ruby-2.2.0/ruby/backward -IC:/Ruby22/include/ruby-2.2.0 -I../../../../ext/wdm -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Ruby22/lib -L.      -lmsvcrt-ruby220  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */
```

After a lot of googling, I found an [explanation](https://github.com/oneclick/rubyinstaller/wiki/Troubleshooting#dll-conflicts-with-devkit-cause-native-gem-install-failures) to a very close but no the exact same error that resolves the error by removing some DLLs. That's obviously not an option here since the offender DLL is kernel32. 

What's even stranger here is that I can get the exact same error by running these 2 simple lines in irb:

```ruby
require 'mkmf'
have_library("kernel32")
```
Running any function from `mkmf` such as `have_header` or `have_const` generate the aforementioned error.

Here is the catch though: I know that the devkit is installed correctly because when I build the gem and install it manually it installs without any problems. However, it would be very tedious to keep doing this while developing WDM and hence I want to be able to compile it.
 
I'm out of options at the moment, so I'm wondering if any of you have any suggestions. Thanks in advance.

**Comment by Azolo** [comment]
When you start `irb` make sure you start it by requiring `devkit`

    > irb -rdevkit

Or requiring first in the `irb` session `require 'devkit'`

Otherwise you will get that error, no matter what. Likewise it sounds like something in your DevKit installation is messed up. If I could get some other information though that would be great.

 - Can you install other gems with native extensions? 
 - Could you try reinstalling the DevKit using `ruby dk.rb install --force` (in the DevKit folder)
 - Do you have any other `mingw` toolchains or `cygwin` in your `PATH` variable?

If it's not your DevKit installation it might be something else in your environment that is breaking it, or possibly something is making it work in my environment.

**Comment by Maher4Ever** [comment]
Hey @Azolo,

Thanks for the reply. Indeed, when I start `irb` with `devkit` required, the error doesn't appear anymore and I get the expected output.

To answer your questions:

1. Yes. I verified the installation by installing the `json` gem as described in the wiki page (with `--platform=ruby`)
2. I just did that. It still doesn't work :(
3. No. The only toolchain or compiler I have is VS 2015, and it's not available from the command line.

I even tried to run the `extconf.rb` file from the command line, but to no avail. Is there any good way to debug what's causing the problem?

**Comment by Maher4Ever** [comment]
*Update*: I was able to compile successfully after doing 2 things:

1. Requiring `devkit` when running `extconf.rb` as follows: ```
ruby -rdevkit extconf.rb
```, or just adding `require "devkit"` to `extconf.rb` then running the script normally.
2. Running the `devkitvars.bat` script from the devkit to configure the `PATH` with the toolchain before compiling.

Any idea why this is needed in my case?

**Comment by Azolo** [comment]
Well, I think there's something wrong with the recognition of `extensions` when you're installing `wdm` then. Do me a favor and when you're installing `wdm` make sure there's a line of output that says:

     Temporarily enhancing PATH to include DevKit...

If there is, then there's something odd going on even though the DevKit is being included. We may need to look and see if there are any other `pre_install` hooks in your gems that might be messing with it.

If there isn't then could I get the contents of: `<RubyRootFolder>\lib\ruby\site_ruby\2.1.0\rubygems\defaults\operating_system.rb`?

**Comment by Maher4Ever** [comment]
I don't see the output line you posted above when compiling WDM when using `rake-compiler`, nor when using `ruby -rdevkit extconf.rb`.

I'm running ruby 2.2 and it seems the file you requested the contents of has been relocated to 
`<RubyRootFolder>\lib\ruby\2.2.0\rubygems\defaults\operating_system.rb`. This file contains:

```ruby
# :DK-BEG: override 'gem install' to enable RubyInstaller DevKit usage
Gem.pre_install do |gem_installer|
  load 'devkit.rb' unless gem_installer.spec.extensions.empty?
end
# :DK-END:
```

**Comment by Azolo** [comment]
Sorry, I said something ambiguous. =X

Do you see it when you run `gem ins wdm`?

**Comment by Maher4Ever** [comment]
Yes. When installing gems I do see it. It's in fact the first line in the output.

**Comment by Azolo** [comment]
ok, so I misread the question. You can install it fine but you want to be able to install it easier while developing for it.

In which case, you need to compile and install it faster without all the hassle. Can you give me a workflow example of how you want it to be/where it fails? Because developing for it you will need to have the DevKit in your path in same way or another.

**Comment by Maher4Ever** [comment]
Thanks for sticking with me while I try to figure out why it isn't working in my environment. My workfollow is pretty simple; I develop the C-code of the WDM extension in VS and compile it outside of VS using `rake-compiler`. While I make changes to the code I have a Guard file that runs `bundle exec rake compile` upon detecting changes to the C source files. 

What fails is the compilation of WDM from `rake-compiler`. Yesterday I was able to get it to work by running the `devkitvars.bat` file before *manually* compiling WDM. Put differently, I wasn't able to use Guard to compile WDM automatically and I had to compile manually every time I made a change. I can change my Guard file to run `devkitvars.bat` and that should probably get it to work, but normally this isn't required.

**Comment by Azolo** [comment]
Yeah, when developing a native extension you're going to HAVE to do something to get the compiler in your `PATH`.

I'm sorry though, I totally misunderstood your issue. I thought that you were having problems installing it, but could build it manually. That is terrible reading comprehension on my part.

My suggestion is to change your `guardfile` to do `bundle exec rake compile -rdevkit` instead of loading `devkitvars` from a hard path. That way you can test with multiple versions of Ruby instead of just the one that corresponds with that DevKit.

**Comment by Azolo** [comment]
Also, here is a semi-explanatory section on the what I'm talking about

[Example Native RubyGem Installations using the DevKit](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit#example-native-rubygem-installations-using-the-devkit)

**Comment by Maher4Ever** [comment]
Thank you very much. Your suggestion to add `-rdevkit` to the compilation command worked perfectly and now I can use my normal workflow once again.

**Comment by Azolo** [comment]
Likewise, sorry I didn't understand the problem. I could have helped earlier. :smiley:
