### ISSUE TITLE
bin/rails server got following error

### ISSUE THREAD

**Issue by manoj10029** [oneclick/rubyinstaller#277]
$ ruby bin/rails server

Could not find gem 'uglifier (>= 1.3.0) x64-mingw32' in any of the gem sources l
isted in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.

**Comment by Azolo** [comment]
Errr, Sorry. That's not really a bug or really any information on a problem you might be having.

Did you try running `bundle install`? If you did and it didn't work can I get some more information? etc...

**Comment by manoj10029** [comment]
Thank you Azolo
Problem is solved now. I use command :

$ gem install uglifier

Bundle had been updated itself. And my server is running now.
