### ISSUE TITLE
Licensing information for RubyInstaller dependencies and DevKit

### ISSUE THREAD

**Issue by Ajedi32** [oneclick/rubyinstaller#281]
The place I work has a very rigorous process for vetting the licenses of software used within the company. RubyInstaller seems to use a BSD license, which is great, but it also seems from the project's README that it downloads a lot of other software from the internet which presumably may not be available under the same license. (Or, in the case of the DevKit and `exe` installers, I believe the software is bundled with the installer itself?)

Is there a list of the software downloaded by RubyInstaller avaliable anywhere, so that I can review their licenses? The RubyInstaller executable mentions Ruby (obviously) and The Book of Ruby in its license agreement, but I'm pretty sure there's way more than that, right? Or is all that software BSD compatible, such that RubyInstaller is able to relicense them under BSD?

**Comment by Azolo** [comment]
You know, that's a good question. I don't really know if we are fully compliant with our licensing or not.

Ruby itself is licensed under the [Ruby License](https://en.wikipedia.org/wiki/Ruby_License).

I know that the DevKit is Mingw64/MSYS and a lot of it is public domain or GNU GPL. 
I don't know about the licenses of the other libraries we use off the top of my head. But `OpenSSL` may be the one that looks like it may be a problem.

      :dependencies => [
        :ffi, :gdbm, :openssl, :yaml, :zlib, :tcl, :tk
      ],

Those are the dependencies we have listed for the Ruby22 rake task.
Those are the only ones that ship with RubyInstaller itself.

All of the files that would be downloaded are in located in the `config` section of source.

If there was a list with all that information what would be the best way to present that information? Also if you see something that isn't right let me know.

@luislavena may be able to give a better answer.

**Comment by Ajedi32** [comment]
> You know, that's a good question. I don't really know if we are fully compliant with our licensing or not.
>
> Ruby itself is licensed under the Ruby License.
>
>[...]
> I don't know about the licenses of the other libraries we use off the top of my head. But OpenSSL may be the one that looks like it may be a problem.

Ruby is actually dual-licensed under the Ruby license and the [BSD 2-clause license](https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29), according to the [`COPYING` file](https://github.com/ruby/ruby/blob/v2_2_2/COPYING) in their repo:

> Ruby is copyrighted free software by Yukihiro Matsumoto <matz@netlab.jp>. You can redistribute it and/or modify it under either the terms of the 2-clause BSDL (see the file BSDL), or the conditions below:

OpenSSL also seems to be under [a BSD-style license](https://www.openssl.org/source/license.html) (though not the BSD license itself). IANAL, but based on the terms there it seems you might need to add a few copyright notices to the RubyInstaller executable to be compliant, assuming OpenSSL is distributed as part of the executable itself and not just downloaded as part of the installation process. Doesn't seem like it should be a big deal though.

---

> ```text
> :dependencies => [
>   :ffi, :gdbm, :openssl, :yaml, :zlib, :tcl, :tk
> ],
> ```
> 
> Those are the dependencies we have listed for the Ruby22 rake task.
> Those are the only ones that ship with RubyInstaller itself.

So that dependency listing is everything distributed with the RubyInstaller executable? :+1: Thanks, that's very helpful. Do you know where I might find a similar listing for the DevKit?

**Comment by luislavena** [comment]
Here is the license information displayed during the installer:

https://github.com/oneclick/rubyinstaller/blob/master/resources/installer/LICENSE.txt

We take no copyright claim but we don't include license information from any of the 3rd party libraries, including Ruby.

IANAL, but patches to collect those and include in the installer are welcome. Even so, not sure if all the licenses are compatible against eachother.

DevKit is MinGW, which is GNU GPL and LGPL, software compiled with it do not require the compiler also be distributed. But again, IANAL.

**Comment by Azolo** [comment]
You can check under the `config` directory if you want, it will be under `devkit.rb` and the files in `compilers/mingw64.rb`. I think, I'm on my phone atm, if they aren't let me know and I'll verify when I get home.

But they are most likely all GPL or Public Domain.

**Comment by Azolo** [comment]
Closing this assuming there's nothing more to do here.
