### ISSUE TITLE
Launching executable in Windows 10

### ISSUE THREAD

**Issue by christiangibbs** [oneclick/rubyinstaller#282]
Hello,

I'm having trouble launching the executable in Windows 10 (x64). I double click the executable and nothing happens other than the Windows loading icon next to the cursor. This even prevents me from deleting the .exe file and only a complete shutdown/restart allows me to do so.

**Comment by Azolo** [comment]
Right, the executable is meant to be used as a command like tool.

When you double click it, it causes it to run indefinitely because it lacks proper context.

You can end the processes through the **Task Manager** just look for `ruby.exe`.

I suggest you take a look at Bosko Ivanisevic's excellent guide at rubyonwindowsguides.github.io

It's pretty involved, but the first chapters give you a bit of a primer on the command line.

**Comment by christiangibbs** [comment]
Thank you for your reply. There's no process in Task manager called ruby.exe, the installer doesn't run and just causes Windows Explorer to not respond. 

I've had a look at Bosko Ivanisevic's guide and it works perfectly for older versions of the installation such as Ruby 2.0.0-p645, but it's the Ruby 2.2.2 (x64) version which is causing the issue.

**Comment by Azolo** [comment]
OH, sorry. You mean the executable installer?
Before I open this back up can you give me some more information?

The exact name of the executable, the your systems chip architecture(32-bit or 64-bit), the anti-virus software you're using (if you're using; Windows Defender counts for this), and the definition version of your anti-virus(if you can find it).

**Comment by christiangibbs** [comment]
No problem :-) yeah the executable installer, apologies for not being more clear. 

Installer version: Ruby 2.2.2 (x64)
Operating System: Windows 10 Home (x64)
Chipset/Processor: Intel Core i7 4790k (x64)
Anti-virus: Windows Defender 
Anti-virus Version: 1.203.2099.0

Please let me know if you need any more information from me.

**Comment by Azolo** [comment]
Ok, so I can't reproduce it, and your definitions appear to be up-to-date.
At first glance it appeared to be similar to #273, but that's doesn't appear to be the case.

Hmmm, lemme think about it.

**Comment by christiangibbs** [comment]
Hmm that does sound like a pretty similar case. I'm going to try and disable a few services and processes in Windows 10, maybe start in safe mode too and let you know if there's any luck and if a particular service/process was causing it.

**Comment by christiangibbs** [comment]
Okay so I booted in to safe mode and attempted to launch the installer. I received a notification from Windows SmartScreen telling me it wasn't available, so I ignored, clicked run anyway and it worked. 

I normal booted Windows and disabled Windows SmartScreen and it worked again! so there's something up with SmartScreeen :/

**Comment by Azolo** [comment]
Gonna try and see if @jasonconradt could point us in the right direction; if he gets some time that is. No Rush.

**Comment by christiangibbs** [comment]
Thank you, Azolo. I can use Ruby and SASS on Mac OS for now, so will look out for updates to this ticket.

**Comment by Azolo** [comment]
@christiangibbs You can always download the 7z version and manually add the location to the `PATH`. That should work perfectly.

**Comment by christiangibbs** [comment]
Oh thanks, I'll look in to doing that then :-)

**Comment by Martlark** [comment]
I had the same issue; double clicking the installer, led to a ruby process, but nothing else happening.  Running from the command prompt fixed it up.

**Comment by jasonconradt** [comment]
Hey guys sorry for the delay. We've been dealing with this one-by-one via signatures based on each escalation and now have a more systemic/holistic fix that should avoid this in most cases going forward for the Inno installer. The issue you were seeing is that we were virtualizing the entire installation sequence and tearing each file apart in a fairly inefficient manner. 

We shipped the fix last night in our engine August release, Windows Update should take care of this automatically, or you can open the Windows Defender UI, click on the "Update" tab, and manually update.  To verify you have the update, open the UI, click on Help -> About and you'll see something like this:

Antimalware Client Version: 4.8.10240.16384
Engine Version: 1.1.12002.0
Antivirus definition: 1.205.102.0
Antispyware definition: 1.205.102.0
Network Inspection System Engine Version: 2.1.11804.0
Network Inspection System Definition Version: 115.10.0.0

Engine Version 1.1.12002.0 is what you're looking for in terms of the one that contains the fix. It goes out to all of our antimalware products (Windows Defender, FEP 2010, SCEP 2012, Microsoft Security Essentials) so they'll all get taken care of with this change.

Please advise if there are any further issues and again apologies for the lack of communication.

Regards,
Jason

**Comment by jasonconradt** [comment]
@christiangibbs  @Martlark  Guys please try with the updated engine per the notes above and let me know if you have any issues.

**Comment by leandroruel** [comment]
sir, same problem here! o/

**Comment by Azolo** [comment]
@leandroruel @Martlark @christiangibbs Hey Guys! Can you give @jasonconradt some feedback on if his suggested fix works?

I don't know why, but I don't seem to be having the same problem. =/

**Comment by leandroruel** [comment]
yes i do what @jasonconradt said. but not work, and after almost one hour, the Ruby installer launch, very weird

**Comment by christiangibbs** [comment]
I managed to get it working after disabling Microsoft SmartScreen, it also seems to be working after Jason's fix to Windows Defender too. Thanks for the help and feedback!

**Comment by jasonconradt** [comment]
Disabling SmartScreen shouldn't have any impact on the scenario I described above, in which double-clicking on the installer seems to have no apparent affect (no UI), but then 5-20 mins later (depending on machine hardware), you'll see the install UI.

@leandroruel  @christiangibbs I can investigate whether Defender is involved in this but need some data. 

From an elevated cmd prompt:

cd c:\Program Files\Windows Defender or C:\Program Files\Microsoft Security Essentials
mpcmdrun.exe -getfiles -all

That will create a file named MPSupportFiles.cab in \ProgramData\Microsoft\Windows Defender or \ProgramData\Microsoft\Microsoft Security Essentials

If it's under 20m, just email me at j a s o n c o n @ m I c r o s o f t. c o m (remove the spaces)

Just a note - there IS potentially sensitive information in these support cabs including machine name, locale, IP address, some registry and machine config settings for example. If you'd rather not share, no worries but it really limits my ability to help understand what's happening. The data will only come to me and reside on my PC (other than being on our email server for a brief period of time), I'll use it troubleshoot, and potentially share this info with others on my team if necessary, then delete it once we're done.

**Comment by leandroruel** [comment]
edited:  cd 'c:\Program Files\Windows Defender\mpcmdrun.exe' -getfiles -all
i put some '' to the spaces between the path string.
but when i run this command i get this:

Set-Location : A parameter cannot be found that matches parameter name 'getfiles'.
On line:1 character:53
+ cd 'c:\Program Files\Windows Defender\mpcmdrun.exe' -getfiles -all
+                                                     ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by Azolo** [comment]
@jasonconradt If I haven't said it before, you're awesome. Thanks for working through this for us.

I'm going to leave this open until October, just in case someone else has this problem. But since the release of Ruby 2.2.3 on Sept. 4, there have been about ~80k downloads and no more issues reported. So everything looks good.

**Comment by jasonconradt** [comment]
Thanks Justin. As an FYI, we’ve made more optimizations for handling the Inno installer beginning with engine September, which dropped on 9/16 (engine version 1.1.12101.0).

Please send me a flare if there any further issues.

Jason
