### ISSUE TITLE
Ruby 2.2.3 has been released!

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller#284]
Hi there,

Ruby 2.2.3 has been released! 

https://www.ruby-lang.org/en/news/2015/08/18/ruby-2-2-3-released/

I'm eager waiting for the windows compiled binary update. Thanks and best wishes.

Kind regards

duytrung

**Comment by Azolo** [comment]
Please checkout this mailing group thread. =) 

https://groups.google.com/d/msg/rubyinstaller/15lypPdoyrI/K-A4W6JFDQAJ

**Comment by duytrung** [comment]
Thanks Azolo! All the best!

**Comment by Azolo** [comment]
I forgot to follow up on this ticket.

Ruby 2.2.3 was released a while back.
https://groups.google.com/d/topic/rubyinstaller/mfvsEw1ATz8/discussion
