### ISSUE TITLE
New feature request: portability of ruby interpreter + devkit

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller#285]
Hi,

I have been thinking about the portability of ruby interpreter + devkit for awhile. This means to put the ruby interpreter + devkit into the USB flash. However, with different computer, the flash drive will be assigned a different drive letter/path. So, when update new gems that require a compiler, the trouble happened.

Is it possible to install the devkit with a relative path and/or run it with a "relative path" eg.".\ruby\devkit" etc..?

Kind regards

Trung Nguyen

**Comment by Azolo** [comment]
It's possible, but extremely brittle. The idea was to create a DevKit gem that more or less accomplished the same thing(including downloading the proper devkit), but it's an undertaking in itself and no one really has had the time.

https://github.com/oneclick/devkit-gem
