### ISSUE TITLE
"Start Command Prompt with Ruby" Shortcut

### ISSUE THREAD

**Issue by wytesk133** [oneclick/rubyinstaller#287]
Target of the shortcut was `C:\Windows\System32\cmd.exe /E:ON /K C:\Program Files (x86)\Heroku\ruby-1.9.3\bin\setrbvars.bat`

It should be `C:\Windows\System32\cmd.exe /E:ON /K "C:\Program Files (x86)\Heroku\ruby-1.9.3\bin\setrbvars.bat"` (with two quotes between the path)

**Comment by Azolo** [comment]
That's Heroku's distribution >_<

You'll have to report it there. Sorry =/
