### ISSUE TITLE
Installation trouble  Windows 10 

### ISSUE THREAD

**Issue by shashwat51** [oneclick/rubyinstaller#288]
C:\DevKit>gem install json --platform=ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe extconf.rb
creating Makefile

make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1
.8.3 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0

**Comment by Azolo** [comment]
At first glance this looks like something is wrong with your DevKit installation.

-----Original Message-----

**Comment by shashwat51** [comment]
Ok I have followed the steps exactly mentioned in the blog .

Ill retry .

**Comment by shashwat51** [comment]
I m sorry I have retried but to no avail.

**Comment by Azolo** [comment]
What blog are you talking about? If I might ask. Also, can you do this step again:

    ruby dk.rb install

except add the `--force` tag.

    ruby dk.rb install --force

Thanks!

**Comment by Azolo** [comment]
@shashwat51 Closing ticket, you're welcome to follow-up if you have any issues.

**Comment by cacti77** [comment]
FYI I had the same problem on Windows 7. Re-running with the --force flag worked for me too...

```
C:\Users\NGGM30N>gem install json --platform=ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20160523-11412-p5wsns.rb extconf.rb
creating Makefile

make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/json-1.8.3/gem_make.out

C:\Users\NGGM30N>cd \rubydevkit

C:\rubydevkit>gem install json --platform=ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20160523-6904-lgt6xx.rb extconf.rb
creating Makefile

make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/json-1.8.3/gem_make.out

C:\rubydevkit>ruby dk.rb install
[INFO] Skipping existing gem override for 'C:/Ruby22'
[WARN] Skipping existing DevKit helper library for 'C:/Ruby22'

C:\rubydevkit>ruby dk.rb install --force
[WARN] Updating (with backup) existing gem override for 'C:/Ruby22'
[WARN] Updating (with backup) DevKit helper library for 'C:/Ruby22'

C:\rubydevkit>gem install json --platform=ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed json-1.8.3
Parsing documentation for json-1.8.3
Installing ri documentation for json-1.8.3
Done installing documentation for json after 2 seconds
1 gem installed

C:\rubydevkit>
```

Not sure why `ruby dk.rb install` didn't work the first time. Possibly because cygwin was on my Windows PATH when I installed the DevKit originally and so I removed it as advised at https://github.com/oneclick/rubyinstaller/wiki/Troubleshooting#mix-and-matching-of-rubyinstaller-with-cygwin-will-fail
