### ISSUE TITLE
Ruby doesn't work when installed in Unicode path

### ISSUE THREAD

**Issue by davispuh** [oneclick/rubyinstaller#289]
When Ruby is installed to Unicode path like  `C:\tēst\Ruby22-x64` then any ruby application will fail with
```
<internal:gem_prelude>:1:in `require': cannot load such file -- rubygems.rb (LoadError)
        from <internal:gem_prelude>:1:in `<compiled>'
```

I think it's most likely Ruby bug.

**Comment by Azolo** [comment]
It is, but it also can depend on your [code page][1]. Try `chcp 1252` and `chcp 65001` and let me know if it's any different.

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx

**Comment by davispuh** [comment]
Changing code pages doesn't change anything, still same error.

**Comment by Azolo** [comment]
Alright, sorry. It's a bug in Ruby and they've looked at it a couple of times. Going to close it here. The RubyInstaller mailing list might have some better advice for you too.
