### ISSUE TITLE
Ruby 1.9.3 gem bat files with "%~dp0ruby.exe" break bundler

### ISSUE THREAD

**Issue by govorunov** [oneclick/rubyinstaller#290]
Hello.

With current "Ruby 1.9.3-p551" package if gems are installed with 'bundle install' command into non default directory, their bat files contain launch string looks like:
@"%~dp0ruby.exe" "%~dpn0" %*
The issue is reproducible when you add "gem 'rails'" to Gemfile and bundle install. Then 'rails' command cannot work.
According to this ticket http://stackoverflow.com/questions/12486985/is-rubygems-creating-the-gem-batch-file-wrong-or-am-i-missing-something it is RubyInstaller patching *.bat files? Or this is just a bug in Rails itself?

I could ask my customers to patch *.bat files with
@"ruby.exe" "%~dpn0" %*
but this is actually unconvenient. Can you confirm the issue is from RailsInstaller or not?

**Comment by Azolo** [comment]
Sorry, I missed this isse but this is something in `rubygems`.
