### ISSUE TITLE
RubyInstaller Ruby 2.2.3 (x64) download has a VIRUS

### ISSUE THREAD

**Issue by Sega100500** [oneclick/rubyinstaller#291]
RubyInstaller Ruby 2.2.3 (x64) download has a VIRUS

not-a-virus:AdWare.Win32.Agent.jjpi
Рекламная программа

**Comment by Azolo** [comment]
It's usually a false positive. Can I get some info on the anti-virus and the definition version you're using?

**Comment by Sega100500** [comment]
@Azolo 
Kaspersky-Antivirus 2015

Ruby 2.2.3 installed
but
Ruby 2.2.3 (x64) is immediately remove by Antivirus

**Comment by Azolo** [comment]
It's running into a false positive.

https://www.virustotal.com/en/file/ca4dadefce6a5adbd4bdd1d960edc0d99d4e05af749e1ed7678476540b7443db/analysis/

I submitted the file to Kaspersky hopefully it will be fixed in their next definition update.

**Comment by Azolo** [comment]
@Sega100500 Just got an email back confirming that it was a false positive and will be fixed next release.

**Comment by Sega100500** [comment]
@Azolo 

All fine! After update KasperskyAntivirus Ruby 64 is successfuly installed
Thanks!
