### ISSUE TITLE
Links to download are not working

### ISSUE THREAD

**Issue by PiotrKostanski** [oneclick/rubyinstaller#292]
Hi, I'm not sure if it is right place to report it, but download links for 
http://rubyinstaller.org/downloads/ does't work at all.
For a past few days when I'm trying to download windows binaries i got ERR_NAME_NOT_RESOLVED.
Is the site still alive?

**Comment by Azolo** [comment]
It indeed is. All of the downloads are hosted from Bintray.

https://bintray.com/oneclick/rubyinstaller/rubyinstaller

Check to see if that link works.

**Comment by PiotrKostanski** [comment]
Yep, works just fine.
