### ISSUE TITLE
Should DevKit be bundled with Ruby Installer?

### ISSUE THREAD

**Issue by TigerMint** [oneclick/rubyinstaller#293]
When trying to get started with Ruby on Rails, creating a new Rails app, this problem below appears. Should the DevKit just be bundled with the Ruby installer? This would lower the barrier to entry.

---------Ruby Installer 2.2.3
Installing json 1.8.3 with native extensions

Gem::InstallError: The 'json' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

**Comment by Azolo** [comment]
@TigerMint This is something comes up every so often, The short answer is there are too many valid reasons it shouldn't.

The biggest reason is that multiple versions of Ruby use the same version of the DevKit. But, RubyInstaller is also repackaged by many different distributions, and the DevKit isn't necessary to run Ruby itself.

Plus with things like [RailsInstaller][1], I feel like there's a pretty good basis for not needing to necessarily bundle the DevKit. Engineyard + contributors do a pretty awesome job on it.

But I do wish that the whole DevKit installation process was easier.

[1]: http://railsinstaller.org/

**Comment by Azolo** [comment]
Closing this, but could provide some context for a future discussion.
