### ISSUE TITLE
IRB and readline with non english keyboards

### ISSUE THREAD

**Issue by neongrau** [oneclick/rubyinstaller#294]
A problem that is bothering me since years. With my (german) keyboard i was never able to type brackets/curly brackets in IRB or in a rails console. When starting irb with "--noreadline" these worked but i can't find a way to disbale readline on rails console and i really don't want to since it disables history on the cursor keys.
Every year or so i try gain to find a working solution wading through posts from 2008 with "$HOME/.inputrc" hacks that never ever worked for me again.

Also today i tried again after installing "ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]" on a freshly installed Windows Server 2012. Still not possible to type brackets in irb with readline. Still no joy with a manually created .inputrc file.

**Comment by Azolo** [comment]
This could be a problem with `rb-readline`, `ruby` itself, or both. Could you let me know which code page you're using, via running `chcp`

**Comment by neongrau** [comment]
C:\Users\Administrator>chcp
Active code page: 850

**Comment by Azolo** [comment]
Try changing your code page to 65001 via `chcp 65001` and see if that fixes it.

**Comment by neongrau** [comment]
That only changes that i now also cannot type any german Umlaut characters. Still no luck with braces.

**Comment by Azolo** [comment]
You can't type Umlaut characters now? Weird `65001` is UTF-8 and it shouldn't affect your OS level keyboard settings.

Lemme look into some things. But the readline implementation RubyInstaller uses is `rb-readline`. It might be a good idea to file a bug report there.

**Comment by MSP-Greg** [comment]
@neongrau

Long story how I ended up here (rdoc testing -> rb-readline).  Habits are habits, and I don't use readline much.  But, my current trunk builds include both a compiled version of readline (`lib\ruby\2.5.0\x64-mingw32\\readline.so`), and `rb-readline`.

When you have a minute, if you could test the compiled version, it would be appreciated.  It passes all the ruby core readline tests except one.  It may have issues with Alt-key combinations.

I've got current builds of trunk at <https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/>. Download & install the `ruby_trunk.7z` file, then rename `lib\ruby\site_ruby\readline.rb` to something else, then you should be able to test the so version.

I'm wondering how functional it is.

FYI, some gems use `readline` for testing, some seem to work better with the so version, others with the rb-readline version...

**Comment by neongrau** [comment]
Problem doesn't occur on windows server >2012. So closing this issue.

**Comment by bieronym** [comment]
Sorry for bringing this issue back from the Dead but i have multiple installations of ruby with no problem in Windows Home, Pro. But in my Laptop with Ruby version 2.6.5p114 and Microsoft Windows 10 Enterprise OS Version: 10.0.18363 N/A Build 18363. When i insert a Unicode character in Greek lets say i try this

```
browser.input(:value => "Εκτύπωση").click 
```

Instead of the usual response, the cmd just crashes and powershell gives [process exited with code 1] and becomes unresponsive.
After days of trying the --noreadline seems to fix the issues.

**Comment by larskanis** [comment]
@bieronym RubyInstaller-2.7.0 has [switched to reline](https://rubyinstaller.org/2020/01/05/rubyinstaller-2.7.0-1-released.html) as the new readline implementation. Could you have a look at it?

**Comment by bieronym** [comment]
Of-course i have only checked  2.6 and 2.5 version and i am pretty sure the problem relies on the Enterprise edition of the windows. I will notify you in a day or two

**Comment by bieronym** [comment]
Yes the ruby-2.7.0 solved everything
