### ISSUE TITLE
The procedure entry point _gmtime64_s could not be located in the dynamic link library msvcrt.dll.

### ISSUE THREAD

**Issue by GeorgeGibson** [oneclick/rubyinstaller#295]
Every time I try to run Ruby, it dies with that error. I'm on Windows XP. Example run:

`ruby dk.rb init`

**The procedure entry point _gmtime64_s could not be located in the dynamic link library msvcrt.dll.**

Why?

**Comment by Azolo** [comment]
Sorry, the current compiler toolchain actually fails on Windows XP and Windows Server 2003.

See #211 and #239 for more information.

**Comment by nilesh-patil-pune** [comment]
Is there any solution for the same

**Comment by prusswan** [comment]
what is the last version that used to work? Ruby 2.0 was still working fine

**Comment by MarkDBlackwell** [comment]
See #271 for a solution.
