### ISSUE TITLE
can't install on windows-7-64-bit

### ISSUE THREAD

**Issue by gcgan** [oneclick/rubyinstaller#296]
it‘s always show the error dialog,like this![rubyinstallererror](https://cloud.githubusercontent.com/assets/56204/11060585/22b21fac-87dc-11e5-85ce-6e5f8739d021.png)

i have try rubyinstaller-2.0.0-p451-x64,rubyinstaller-2.0.0-p645-x64,rubyinstaller-2.1.7-x64,rubyinstaller-2.2.3-x64

**Comment by Azolo** [comment]
Sorry, I have no idea what that says. =(

**Comment by gcgan** [comment]
it means 
>This file version and the Windows version you are running is not compatible. Please check your computer's system information to understand x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher

**Comment by luislavena** [comment]
@gcgan that is a corrupt installer. If you're constantly getting that, try to check if your system has been infected by a virus/trojan or similar.

Download the binaries and compare the md5/sha1 signatures from the announcement email or the companion files.

**Comment by Azolo** [comment]
@luislavena Thanks, I wouldn't have gotten that.
