### ISSUE TITLE
gcc version for RubyInstaller-2.3 ?

### ISSUE THREAD

**Issue by larskanis** [oneclick/rubyinstaller#297]
I would like to prepare [rake-compiler-dock](https://github.com/rake-compiler/rake-compiler-dock) for the ruby-2.3 release. Will RubyInstaller-2.3 still use the gcc-4.7.2 and msys based devkit, as RubyInstaller-2.2?

**Comment by Azolo** [comment]
That would be easiest thing for me. But possibly not the best solution.

So if you have any thoughts let me know otherwise I'm on default with the current one.

**Comment by larskanis** [comment]
The same devkit is also the easiest thing for me.

I did some experiments with Msys2 last year, but wasn't happy with the way it integrates into Windows. Maybe things have changed, in the meantime.

Gcc-4.8+ has changed static linking. This is probably not an issue, if RubyInstaller bundles the matching libgcc DLL (and maybe `libwinpthread-1.dll` and `libstdc++-6.dll` as well ). In this case I would update to the equal gcc version for ruby-2.3, so that it plays together nicely.

**Comment by Azolo** [comment]
I know that @jonforums and @shirosaki we working on MSYS2, and I think it's probably in a pretty good state now and I think @jonforums statically linking `libstdc++-6.dll` but I'm not super sure.

However, I think it's something we should consider in maybe for 2.4 or Ruby 3 unless someone has a really compelling reason to include it before then.

**Comment by larskanis** [comment]
@Azolo OK, thank you for this information.

**Comment by sodabrew** [comment]
In #232 I asked: I found that the MinGW in present versions of DevKit are not providing some newer (read: available since Windows XP...) getaddrinfo constants: eventmachine/eventmachine#659

These were added to MinGW somewhat recently: http://sourceforge.net/p/mingw-w64/mailman/message/33056995/

Even if we don't bump the entire compiler package, is it possible to update the MinGW headers?

**Comment by larskanis** [comment]
FYI: rake-compiler-dock-0.5.0 is already released with support for Ruby-2.3 and an unchanged tool chain: https://rubygems.org/gems/rake-compiler-dock
