### ISSUE TITLE
Error Message: From c:/opt/Ruby187/bin/pdfbeads:19

### ISSUE THREAD

**Issue by rain81388** [oneclick/rubyinstaller#298]
Hi. I'm using the Homer app which uses pdfBeads to use OCR and create a searchable pdf from .tif files. I keep getting this message

"From c:/opt/Ruby187/bin/pdfbeads:19"

Any idea what it means and what I can do about it?

**Comment by Azolo** [comment]
I'm sorry, I honestly have no idea. Ruby 1.8.7 was before my time and isn't supported anymore. The best bet would be to reach out to the app package creators.
