### ISSUE TITLE
ruby 2.2 stopped working with Windows 10

### ISSUE THREAD

**Issue by amitkayal** [oneclick/rubyinstaller#301]
I have windows 10 installed in my computer and ruby is failing with error "ruby interpreter (CUI) 2.2.p95[j386-mingw32] has stopped working".

Had a look at windows event viewer and following info where it shows that windows is not able to retrieve module name.

===Windows Event viewer log file=============
Faulting application name: ruby.exe, version: 2.2.2.95, time stamp: 0x552f34ec
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x050fa840
Faulting process id: 0x1488
Faulting application start time: 0x01d140aae12a401c
Faulting application path: F:\Amit\Ruby\Ruby22\bin\ruby.exe
Faulting module path: unknown
Report Id: 8d23abae-cd72-4116-80a8-f15234366ffb
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Azolo** [comment]
I honestly have no idea, can you give more information on the circumstances it is failing?

**Comment by voronoipotato** [comment]
Did you upgrade after installing ruby or did you install ruby after win 10?

**Comment by ccoenen** [comment]
@amitkayal could you give more steps to reproduce, or describe what you're trying to do? I have a windows 10 machine, and "simple" things seem to work without issue with ruby 2.2.3 in both 32 and 64 bit on a 64 bit machine.

**Comment by luislavena** [comment]
Hello @amitkayal 

There isn't enough information in this report for us to help you determine what is going on and why it crashed.

Please provide details as mentioned in our mailing list:

https://groups.google.com/d/topic/rubyinstaller/cAKLJmhfG-U/discussion

And also include the script/program you're attempting to execute.

If is not possible to share, please try to find the minimal scenario that reproduces the issue.

Once you have that, please respond and we will evaluate to reopen the issue.

Cheers.

**Comment by vipulgnair** [comment]
Check that Ansicon is installed. if so try uninstalll that and try. it worked for me

**Comment by acesudhir** [comment]
There is a easier way out. Uninstall ansicon version currently installed and go for a lower version of ansicon. I had ansicon160 installed, i uninstalled ansi-160 and then installed version ansi152 and this resolved my crash problem.
