### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by suresh-webdeveloper** [oneclick/rubyinstaller#304]
site is not opening

**Comment by suresh-webdeveloper** [comment]
![asasas](https://cloud.githubusercontent.com/assets/6688657/12389775/fc7ccf0c-be00-11e5-9f56-f45999bd0449.JPG)

**Comment by Azolo** [comment]
It looks like it's working here. The error you're getting is also a connection reset error. It might have been an intermittent issue, can you confirm it is still not working for you?

**Comment by suresh-webdeveloper** [comment]
yeah still i am facing same issue

On 18 January 2016 at 18:59, Justin Baker <notifications@github.com> wrote:

> It looks like it's working here. The error you're getting is also a
> connection reset error. It might have been an intermittent issue, can you
> confirm it is still not working for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oneclick/rubyinstaller/issues/304#issuecomment-172527337>
> .
>



-- 
---------------------------
Thanks & Regards,
Suresh Babu
Phone:9177389695

**Comment by luislavena** [comment]
downforeveryoneorjustme.org reports site is up:

http://www.downforeveryoneorjustme.com/rubyinstaller.org

Most likely the issue you're facing is a corporate proxy or our internet provider is blacklisting RubyInstaller.

I recommend check from another connection and if that still persist, please reply back.

Cheers.
