### ISSUE TITLE
Upgrade version of OpenSSL included with ruby

### ISSUE THREAD

**Issue by spiffycoffee** [oneclick/rubyinstaller#313]
It seems the version of OpenSSL (1.0.1l) included with the ruby stdlib contains a regression in regards to certain HTTPS requests. See here: [https://github.com/jekyll/jekyll-gist/issues/30](https://github.com/jekyll/jekyll-gist/issues/30)

Any possibility of upgrading it to a newer version?

**Comment by Azolo** [comment]
I have to build it and upload it to Bintray based off the knapsack recipes.

I rushed this last release and didn't get to it. I'll do it soon though.

Feel free to add new recipes to https://github.com/oneclick/knapsack-recipes for the version you want. =)

You can in theory (I've done it, but I can't promise support for the other versions) drop the newer version of the dlls into the `ruby/bin` folder. OpenSSL is pretty good about not making breaking changes.

**Comment by TWiStErRob** [comment]
Any news? I'm still getting the error, just downloaded the latest Ruby I could find that's compatible with https://pages.github.com/versions (2.3.1)
```
> ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]
> ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.1l 15 Jan 2015
```
I tried replacing 
 * `p:\tools\lang\ruby-2.3.1-x64-mingw32\bin\ssleay32.dll`
 * `p:\tools\lang\ruby-2.3.1-x64-mingw32\bin\libeay32.dll`

with the latest from https://indy.fulgan.com/SSL/, but to no avail.

Ruby code is still using `p:\tools\lang\ruby-2.3.1-x64-mingw32\lib\ruby\2.3.0\x64-mingw32\openssl.so` which is that older version and I couldn't find a replacement for it yet.

**Comment by TWiStErRob** [comment]
This helped in the end: https://gist.github.com/fnichol/867550#the-manual-way-boring

**Comment by coderjoe** [comment]
Openssl 1.0.2j is out now and the 1.0.2 branch is the LTS branch. 1.0.1 is no longer supported and there have been quite a few security patches on the 1.0.2j tree.

Is there anything I can do to help get this updated in rubyinstaller? Is it as simple as updating the dependency URL to the openssl-1.0.2j package provided by the OpenKnapsack bintray package?

**Comment by Azolo** [comment]
> Is it as simple as updating the dependency URL to the openssl-1.0.2j package provided by the OpenKnapsack bintray package?

@coderjoe Indeed, but maintain those OpenKnapsack packages so I had to build `1.0.2j` first. They will be in the next RubyInstaller releases that I will have out in the next couple of days.

**Comment by coderjoe** [comment]
@Azolo you're going to release a new version over the next couple of days? That will be incredibly helpful! Thank you very much and let me know if there's anything I can do to help!

**Comment by Azolo** [comment]
The newest RubyInstaller releases include `OpenSSL 1.0.2j`.

**Comment by coderjoe** [comment]
Thank you very much @Azolo !
