### ISSUE TITLE
Core API documentation for the Module class is missing a section

### ISSUE THREAD

**Issue by paul-calvelage** [oneclick/rubyinstaller#316]
Ruby-doc.org provides documentation of the private instance methods of the Module class (see http://ruby-doc.org/core-2.2.4/Module.html).  The CHM documentation provided for download from http://rubyinstaller.org/downloads does not contain this section.

I am using the Ruby 2.2.4 Core API Reference and was specifically looking for documentation of `attr_accessor`, `attr_reader`, and `attr_writer` in `ruby22-core.chm`.  It's not there.

It appears that the entire section of private instance methods, from `alias_method` to `using`, is missing from the CHM file.

**Comment by Azolo** [comment]
This should have been fixed in #308, but I don't know if I released 2.2.4 before or after that.

Could you check the newer versions of the CHMs and let me know if it isn't fixed?

If it's not I'll reopen this issue.

**Comment by paul-calvelage** [comment]
The new 2.1.9, 2.2.5, and 2.3.1 CHMs look fixed, so I agree with closing this.  Good discussion in #308.  Thanks!
