### ISSUE TITLE
Ruby 2.3.0 (x64) version name error

### ISSUE THREAD

**Issue by windthunder** [oneclick/rubyinstaller#323]
I try to install rails 5.0.0 but get some problem.

C:\Users\Administrator.MS-20151231DMDF>gem install rails 5.0.0
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Fetching: concurrent-ruby-1.0.2.gem (100%)
Successfully installed concurrent-ruby-1.0.2
Fetching: sprockets-3.6.0.gem (100%)
Successfully installed sprockets-3.6.0
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-4.2.6.gem (100%)
Successfully installed activesupport-4.2.6
Fetching: mini_portile2-2.0.0.gem (100%)
Successfully installed mini_portile2-2.0.0
Fetching: nokogiri-1.6.7.2-x64-mingw32.gem (100%)
ERROR:  Error installing rails:
        nokogiri requires Ruby version < 2.3, >= 1.9.2.
ERROR:  Could not find a valid gem '5.0.0' (>= 0) in any repository

version should be 2.3.0. not 2.3,

**Comment by daniel-rikowski** [comment]
This is no bug in RubyInstaller. The Nokogiri team simply hasn't released a *stable* version for Ruby 2.3. 

You have to use the pre-release version. Add `gem 'nokogiri', '>= 1.6.8.rc3'` to your Gemfile and then execute `bundle update`

**Comment by dmajkic** [comment]
Also rails 5.0.0 is not released yet.

You can install latest prerealise version with

     gem install rails --pre
