### ISSUE TITLE
No PathCch functions

### ISSUE THREAD

**Issue by djberg96** [oneclick/rubyinstaller#328]
It seems the various PathCch functions from pathcch.lib are not available when using the devkit. These were added in Windows 8 and later, and supplant the older Path functions, e.g.` PathCchAppendEx` vs `PathAppend`.

    require 'mkmf'
    have_library('pathcch')

Using a Ruby compiled with Visual Studio, the above snippet will return true, while the Devkit returns false. Can they be supported?

**Comment by Azolo** [comment]
@djberg96 That would depend on the compiler toolchain, right? In which case unless you compiled with a different toolchain than RubyInstaller currently uses, which is rbenv's `mingw64-4.7.2` build, it would not be supported.

**Comment by djberg96** [comment]
@Azolo Ah, so it's really up to the mingw toolchain, got it.

**Comment by djberg96** [comment]
@Azolo Any chance of upgrading the toolchain that RubyInstaller uses?
