### ISSUE TITLE
I installed ruby, now how do I execute ruby code?

### ISSUE THREAD

**Issue by Enprogames** [oneclick/rubyinstaller#330]
I am on windows 10. I installed ruby 2.3.0, I checked all of the boxes in the installer, I kept the default install path, but whenever I try to execute a .rb file, it just closes right away. Is there any way to keep the window open and use my program?

**Comment by dmajkic** [comment]
Right clik on start, and choose "Command Prompt", than cd to the directory where your rb file is.
Run it with `ruby yourrbfile.rb`
