### ISSUE TITLE
No Ruby base version should be the default

### ISSUE THREAD

**Issue by MarkDBlackwell** [oneclick/rubyinstaller#332]
Currently, the output of `rake --tasks` includes:

    rake default                   # Build Ruby 2.3

What's the use case for defaulting to a Ruby base version—whether activated manually, or by scripts? What utility does it have?

Syntax differences among Ruby base versions IMO would seem to preclude such a default from being generally useful.

Instead of a default Ruby base version, IMO the README should tell people to do `rake --tasks` and then to pick a Ruby base version.

**Comment by Azolo** [comment]
Ruby 1.8 was the default task for years, so I think that Ruby 2.3 is a reasonable default.

However, if you think something else is better as a default `rake` task then I would be open to looking at a Pull Request. =)

**Comment by MarkDBlackwell** [comment]
As you may know, Rake doesn't need a default task. In that case, it merely says, "Don't know how to build task 'default' (see --tasks)".

Would you be open to (looking at) a Pull Request which simply unspecifies the default task? In itself, that might be an easy one.

Such a Pull Request might be useful, in order for the userbase (and documentation) to catch up, before a new default task is created, later. The new default task would be wholly unrelated to what has gone before.

Better, that Pull Request should include all consequential documentation changes (and be roughly synchronized with another Pull Request to the website's repository).

So, I'll think about it. :)

**Comment by Azolo** [comment]
I would be open to a Pull Request like that. =)

Though the website is in limbo atm. Right now it's running off a CMS and while I think everyone wants to migrate it to another medium, no one has done the work yet.
