### ISSUE TITLE
2.3.1 Installer created with RubyLibVersion=2.3.0?

### ISSUE THREAD

**Issue by keeganwitt** [oneclick/rubyinstaller#334]
FYI, it looks to me like the 2.3.1 installer was run with the incorrect argument of RubyLibVersion=2.3.0 because it put stuff in C:\Ruby23\lib\ruby\2.3.0.

**Comment by Azolo** [comment]
That's the correct spot. Those folders only change when there's an breaking ABI (Application Binary Interface) change. Which only happens on Minor level changes these days. i.e. 2.4.0

Run `ruby -v` in the console and it will be the correct version. =)

**Comment by keeganwitt** [comment]
Ah, OK.  I know the version installed was correct, I just thought it had the wrong folder name.  Sorry for the extraneous bug report.
