### ISSUE TITLE
DevKit Installation Instructions are not complete

### ISSUE THREAD

**Issue by marko-avlijas** [oneclick/rubyinstaller#336]
I've had this same thing happened to me:

http://stackoverflow.com/questions/27239491/cannot-install-gem-make-is-not-recognized-as-an-internal-or-external-command-o

So I'd get this error message 
```make is not recognized as an internal or external command operable program or batch file```

even though I followed all the steps from https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

Answer by Kalyan fixed it. 

What needs to be done is to update this https://github.com/oneclick/rubyinstaller/wiki/Development-Kit
to include last step from the anwer 

```
cd C:\RubyDevKit
ruby dk.rb init
ruby dk.rb install
devkitvars.bat
```

**Comment by Azolo** [comment]
`devkitvars.bat` loads the devkit into the environment and the requirement of doing that means that something is broken in your devkit installation.

Basically, the _devkit installation_ is doing what `devkitvars.bat` is doing, except only in the process on demand as required.

If you're using the `64 bit` version, then the `ruby dk.rb init` command doesn't work properly and you will have to edit the generated file manually.
