### ISSUE TITLE
 ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by paredonsur** [oneclick/rubyinstaller#339]
Hello,

He was using ruby 1.9.3 and now install ruby 2.2.5

in os Windows 7 

The DevKit first install in the same directory c: / Ruby22

Then it out there and install it in C: / DevKit

the config.yml was as follows:

# ---
# - C: / ruby19trunk
# - C: / ruby192dev
#
---
- C: / Program Files (x86) /ruby-1.9.2
- C: / Program Files (x86) /Heroku/ruby-1.9.3
- C: / Ruby193
- C: / Ruby22

What strikes me is that the only gem that will not let me install is to json.

In fact the app on localhost me is working with Ruby 2.2

I get the following error when installing the gem json :
       
C:\cRuby\facturagratis-prueba>gem install json --platform=ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
C:/Ruby22/bin/ruby.exe -r ./siteconf20161006-8004-nysx45.rb extconf.rb
creating Makefile

current directory: C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
make "DESTDIR=" clean

current directory: C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
make "DESTDIR="

make failed, exit code 1

My GEM ENV  :

RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.7
  - RUBY VERSION: 2.2.5 (2016-04-26 patchlevel 319) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby22/lib/ruby/gems/2.2.0
  - USER INSTALLATION DIRECTORY: C:/Users/Gabriel/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: C:/Ruby22/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby22/bin
  - SPEC CACHE DIRECTORY: C:/Users/Gabriel/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/Ruby22/lib/ruby/gems/2.2.0
     - C:/Users/Gabriel/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files\Common Files\Microsoft Shared\Windows Live
     - C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live
     - C:\ImageMagick
     - C:\Ruby22\bin
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\
     - c:\Program Files\Microsoft SQL Server\100\Tools\Binn\
     - c:\Program Files\Microsoft SQL Server\100\DTS\Binn\
     - c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\
     - c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\
     - C:\Program Files (x86)\Heroku\bin
     - C:\Program Files (x86)\ruby-1.9.2\bin
     - C:\Program Files\git\bin
     - C:\Program Files\git\cmd
     - C:\Program Files\nodejs\
     - C:\Program Files\Google\Google Apps Sync\
     - C:\Program Files\Google\Google Apps Migration\
     - C:\Program Files (x86)\Windows Live\Shared
     - C:\Program Files (x86)\Skype\Phone\
     - C:\Ruby22\bin
     - C:\ImageMagick
     - C:\MinGW\bin
     - C:\Ruby193\bin
     - C:\Program Files\PostgreSQL\9.2\bin
     - C:\Users\Gabriel\AppData\Roaming\npm\

**Comment by Azolo** [comment]
Ruby 2+ use a different DevKit than Ruby 1.9.3.

You can find more information on the download page.

**Comment by paredonsur** [comment]
Yes of course
The devkit does not work me is the corresponding Ruby 2+

**Comment by paredonsur** [comment]
This is exactly the devkit install DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe (32bits)
