### ISSUE TITLE
Cannot install tools, SSL certificate verify failed

### ISSUE THREAD

**Issue by shoprex** [oneclick/rubyinstaller#343]
I made the following command: "gem install sass" and get this error message:
"Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"
I use Windows 10 x64 and installed ruby today from http://rubyinstaller.org/ and has the version 2.3.1

**Comment by Azolo** [comment]
See #338
