### ISSUE TITLE
Http instead of https being used for download links.

### ISSUE THREAD

**Issue by picatz** [oneclick/rubyinstaller#346]
**How I insecurely installed ruby and why and things:**

At the following url : [ruby-lang.org/en/documentation/installation/#rubyinstaller](https://www.ruby-lang.org/en/documentation/installation/#rubyinstaller) there is a link to the [ruby installer](https://rubyinstaller.org/) website. Note: unlike the link I have made for this issue, the ruby-lang.org website has the following [link](http://rubyinstaller.org/) which is an "insecure" version of the [ruby installer](https://rubyinstaller.org/) website because it's **not** bering served with https. This http version also seems to be the version I am directed to from the google index of "downloads" from what I can tell:
![googley](https://cloud.githubusercontent.com/assets/14850816/20636853/c2728c38-b342-11e6-96c8-f2bca5df804e.png)

The following is a screenshot of what I'm talking about:
![screen shot 1](https://cloud.githubusercontent.com/assets/14850816/20636463/64fe30d6-b33b-11e6-9478-dbdb0ee1a0ba.png)

When you click on this link, you're taken to an insecure version of the ruby installer website. Note the lack of the green lock:
![screen shot 2](https://cloud.githubusercontent.com/assets/14850816/20636490/09bcc2d6-b33c-11e6-8121-f15c5017cf68.png)

So, if I were to want to install ruby ( which I did ), I would be doing so via an insecure connection opening myself up to attacks. _Moreover_, the actual ruby installer website is serving their default download links with http as well ( from what I can tell ):
![screen shot 3](https://cloud.githubusercontent.com/assets/14850816/20636844/8aecfbb8-b342-11e6-95d1-cabc23712b5c.png)

I've yet to do any testing to see how vulnerable this current setup is. But, knowing what I know about what should and _shouldn't_ be served over https -- well, I just think these situations warrant it. 

When I update or install packages with brew -- that seems to be done over https. I can configure apt to use https. Python's [download page](https://www.python.org/downloads/) seems have all of its download links with https.

Perhaps I could just add a little _s_ to the link from the downloads page to make it https? 
`http://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.3.1.exe`
I haven't tried. Just tried. 
`https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.3.1.exe`
Seems to have worked just to the same.

I think it should be the default link to install if the option is there for an extra layer of security by default.

**Comment by picatz** [comment]
**Note:** this could totally have been an issue opened in the wrong place. 

But, ya' know, you only live once, right?

**Comment by picatz** [comment]
Moved to [probably the right place](https://github.com/oneclick/rubyinstaller.org/issues/9) for this.

**Comment by picatz** [comment]
UNLESS THIS IS THE RIGHT ONE? WHAT IS THIS PLACE?

**Comment by vais** [comment]
@picatz I am as confused as you are at this point... https://github.com/oneclick/rubyinstaller.org does not seem to match what's on the rubyinstaller.org website, so I'm not sure how to make a PR for the website to fix this issue. bintray.com seems to support https just fine, so it's only a matter of updating the links to use https instead of http, but where's the website source? cc @Azolo

**Comment by vais** [comment]
@picatz btw I made a PR to update the link to rubyinstaller.org on the ruby-lang site, https://github.com/ruby/www.ruby-lang.org/pull/1514 Thanks!

**Comment by picatz** [comment]
Awesome!

**Comment by luislavena** [comment]
All the download links in rubyinstaller.org are now https.

**Comment by picatz** [comment]
Thanks!

**Comment by vais** [comment]
@luislavena sorry to bother you, is the source of rubyinstaller.org not on GitHub? The repo that is on GitHub does not seem to match the site 😕

**Comment by luislavena** [comment]
@vais see conversation on this thread: https://github.com/oneclick/rubyinstaller/issues/309#issuecomment-192327048 (starts at that comment with explanation of repos and current setup).

**Comment by vais** [comment]
Awesome, thank you @luislavena. And for what it's worth, we miss you and appreciate all you have done and continue to do despite having officially stepped away from the project quite a while ago. Again, thank you.
