### ISSUE TITLE
Include Ruby in the Ruby installer

### ISSUE THREAD

**Issue by HadashiBlacksky** [oneclick/rubyinstaller#347]
Hi, I love all the tutorials included with the Ruby installer, but I think it's about time to take the leap and actually include Ruby in the Ruby installer. Or, indeed, any compiler. At all. ;)

Version downloaded: 2.3.1

**Comment by luislavena** [comment]
RubyInstaller includes Ruby.

Ruby is a command line application. Special icons have been added to the Program menu that you can access to start a *Command Prompt* with Ruby in the PATH (making `ruby` command accessible) or use the Interactive Ruby (IRB).
