### ISSUE TITLE
Ruby 2.3.3 Windows Installer stopped by Windows Defender on Windows 10

### ISSUE THREAD

**Issue by Sega100500** [oneclick/rubyinstaller#349]
Ruby 2.3.3 Windos Installer stoped by Windows Defender on Windows 10
And Ruby Windows Installer not run.
Possible WD see it as virus.

**Comment by luislavena** [comment]
Might be false positive, as reports for the binaries from Virus Total are clean:

- https://www.virustotal.com/en/file/43110f9bcd8a067d69409507cad6a43f1fcf05e8bd64d096dd9df47475de50f3/analysis/1481108219/
- https://www.virustotal.com/en/file/3d0a4ad06c5503e1cb88827443593969e689ac96b5161140b08f0becb7b792cf/analysis/1481099906/

You can also check and compare the MD5 and SHA signatures of the files from BinTray:

https://bintray.com/oneclick/rubyinstaller/rubyinstaller/2.3.3#files

**Comment by Azolo** [comment]
It is, submit the Installer at https://www.microsoft.com/en-us/security/portal/submission/submit.aspx and it's usually updated as clean in the next Definitions release.

**Comment by Sega100500** [comment]
@Azolo 
I try Ruby Installer 2.3.3 x64 and x32.  Both stopped by WD :-(
When next Definitions release?

**Comment by Azolo** [comment]
I have no idea, but as long as you submit it through the site I linked it tends to be pretty quickly.

**Comment by daniel-rikowski** [comment]
I had no problem on two different Windows 10 and a Windows 8 workstations today. Make sure your files are not tainted somehow! (By comparing the hash signatures)

**Comment by Sega100500** [comment]
@daniel-rikowski 
I have encountered similar in other versions of RubyInstaller. It problem in antivirus. 
And... how check hash signatures on Windows, and where signatures for Ruby WindowsInstaller?

**Comment by Sega100500** [comment]
Hmmm... no Windows Defender, but Filter Windows SmartScreen

**Comment by Azolo** [comment]
#273 is pretty informative about the current situation.

Make sure you have the latest Windows Updates (including Edge updates) as well.

**Comment by Sega100500** [comment]
@Azolo 
Can ignore the warning of 'Filter Windows SmartScreen' and install anyway.
But still warnings is present.
I ignore warnings and install Ruby.

**Comment by latimercaleb** [comment]
Tried to install version 2.5.0-2x64 on windows 10 and received a block from defender

**Comment by luislavena** [comment]
@latimercaleb is quite common that antivirus definitions flag certain software as false positive.

Please see previously provided links, confirm the file against VirusTotal website.

Cheers.
