### ISSUE TITLE
Ruby 2.4.0 released

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller#350]
Hi maintainer,

Just a remind in case you missed the news: ruby 2.4.0 release. Please update the installer for windows platform.

Thanks a heap! :-)

**Comment by Azolo** [comment]
Yep, please see #348

**Comment by anikolaev** [comment]
Sorry for asking but it was released month ago. What is the current status? I see some discussion in pull request comments but it was stopped 22 days ago. When it is expect to release new version? There is almost no options for Windows?

**Comment by vais** [comment]
@anikolaev for what it's worth, it looks like the effort to release Ruby 2.4 for Windows has shifted here: https://github.com/larskanis/rubyinstaller2

**Comment by larskanis** [comment]
I uploaded a first release candidate: https://github.com/larskanis/rubyinstaller2/releases/tag/2.4.1-1rc1
You're welcome to try it out and give some feedback.

**Comment by luislavena** [comment]
Lars work on RubyInstaller2 has been migrated to the OneClick organization:

http://github.com/oneclick/rubyinstaller2

And a release candidate has been uploaded for testing (see above link).

Future issues re: Ruby 2.4.x will be addressed in that repository.

Thank you.
