### ISSUE TITLE
Switch to RubyInstaller2 for Ruby-2.4 ?

### ISSUE THREAD

**Issue by larskanis** [oneclick/rubyinstaller#352]
At the last days, I was working on the MSYS2 based [RubyInstaller2](https://github.com/larskanis/rubyinstaller2) . IMHO it is now roughly on the level of the current RubyInstaller. There are some outstanding issues that I've documented on the [issue list](https://github.com/larskanis/rubyinstaller2/issues). I'll work on these in the next days and will do more tests on our dev and production systems at work.

So to my question: Shall we switch to [RubyInstaller2](https://github.com/larskanis/rubyinstaller2) for the Ruby-2.4 branch? This would mean:

1. Everyone should test for regressions compared to the current RubyInstaller and [add/solve issues](https://github.com/larskanis/rubyinstaller2/issues).
1. Move RubyInstaller2 to https://github.com/oneclick .
1. Update rubyinstaller.org for MSYS2 stuff. (And remove Ruby-1.8/1.9 related)
1. Answer a lot of questions related to MSYS2 and pacman.
1. Going EOL with MSYS1 based RubyInstaller-2.3 in 2 to 3 years and support both environments until then.

This all will probably take a while, but my hope is to have a release quality in 2-3 months.

**Comment by ccoenen** [comment]
A few simple tests with 2.4.0-4 did not turn up any oddities.

**Comment by johnnyshields** [comment]
@larskanis @Azolo @luislavena can we move forward with moving RubyInstaller2 to one-click and releasing Ruby 2.4?

**Comment by luislavena** [comment]
Hello @larskanis, I've been stalking your work on the new repository but I've been a bit busy with work.

It is possible for us to agree/meet to discuss these steps this week? You can email me at `<username on GitHub>@<gmail dot com>`

Thank you.

**Comment by luislavena** [comment]
For the record, I think steps covered by first comments are good, but will introduce a few more details:

- Move this repository to `rubyinstaller-legacy`
- Document this repository is for old versions of Ruby
- Move `rubyinstaller2` as `rubyinstaller`
- Add a paragraph about old (legacy) version.

**Comment by larskanis** [comment]
@luislavena Sorry for responding so late! First I was too busy with work and second I had several outstanding issues on the agenda with rubyinstaller2, which I wanted to have solved before doing further steps.

Are you sure to rename this repository? This invalidates all links to the repository. I would leave it where it is and document the situation in both repositories.

**Comment by ccoenen** [comment]
personally, I do not see any advantage in switching the repositories around. And the disadvantage of invalidating a huge amount of links is a very valid point, in my opinion. I believe this would also create weird confusion for everyone just `git pull`-ing into an existing repository. I don't even know what git would do in such a case.

wouldn't adding a note to the readme of rubyinstaller(1) front and center achieve basically the same goal?

**Comment by luislavena** [comment]
Hello @larskanis, actually renaming the repository will not produce any broken link thanks to GitHub redirect support.

Take for example sqlite3-ruby, which was hosted on my account. From emails, here is a link:

https://github.com/luislavena/sqlite3-ruby/issues/85

It performs a proper redirect to the new location (sparklemotion/sqlite3-ruby):

Same thing goes for Wiki and other elements, including direct links to commits, releases and others.

> I believe this would also create weird confusion for everyone just git pull-ing into an existing repository. I don't even know what git would do in such a case.

@ccoenen the total number of clones for this repository are less than [20 per day](https://github.com/oneclick/rubyinstaller/graphs/traffic), that might be triggered by some build infrastructure or similar. I think when the number is higher than 100 we should be considering that affecting a big user base.

> wouldn't adding a note to the readme of rubyinstaller(1) front and center achieve basically the same goal?

In my painful experience through the years working with RubyInstaller I would say no, people don't read.

**Comment by luislavena** [comment]
Is worth to mention that something similar to this was done recently by Homebrew.

**Comment by larskanis** [comment]
@luislavena Github redirection only works as long as there is no new repository at the old name. If I understand you right, your proposed rename is:
```
oneclick/rubyinstaller -> oneclick/rubyinstaller-legacy
larskanis/rubyinstaller2 -> oneclick/rubyinstaller
```
Links to larskanis/rubyinstaller2 will still work, but it will invalidate links to issues, wiki, commits, etc. of oneclick/rubyinstaller.

**Comment by johnnyshields** [comment]
@larskanis I think that's ok... most of the old issues can be closed anyway and the wiki can be copied/moved over...

**Comment by larskanis** [comment]
I uploaded a first release candidate: https://github.com/larskanis/rubyinstaller2/releases/tag/2.4.1-1rc1
It has everything built in now, that I planned for the first release. I also added a [CHANGELOG](https://github.com/larskanis/rubyinstaller2/blob/master/CHANGELOG.md) that tries to list changes compared to RubyInstaller(1). You're welcome to try it out and give some feedback.

**Comment by luislavena** [comment]
Hello,

RubyInstaller2 repository has been migrated to OneClick organization.

https://github.com/oneclick/rubyinstaller2

A release candidate has been uploaded by Lars:

https://github.com/oneclick/rubyinstaller2/releases/tag/2.4.1-1rc1

We now require README updates to reflect the changes and later on updates to the website.

**Comment by larskanis** [comment]
I've pushed another (and hopefully final) [prerelease](https://github.com/oneclick/rubyinstaller2/releases/tag/2.4.1-1rc2).

I also did some work to move rubyinstaller.org to a static site. It is stored in the [rubyinstaller2 repo](https://github.com/oneclick/rubyinstaller2/tree/master/docs) and hosted [on github](https://oneclick.github.io/rubyinstaller2/). The site is fully self contained and doesn't use external resources. I updated the texts regarding RubyInstaller2 and added a possible release post for Ruby-2.4. Feel free to open pull requests if the wording is not good. Please have a look: https://oneclick.github.io/rubyinstaller2/

I took jekyll as the site generator because it is well supported by github. And I stored it within the rubyinstaller2 repository to make release automation easier.

@luislavena If you agree to the switch of rubyinstaller.org to github, it is required to enable a custom domain in the [github settings](https://github.com/oneclick/rubyinstaller2/settings) and to set the CNAME and ANAME records as described in the github docs.

**Comment by ccoenen** [comment]
Is there anything in the RC2 that should be tested in particular?

**Comment by larskanis** [comment]
@ccoenen Thanks for asking! All 3 changes are possibly interesting:

1. Allow MSYS2 to be shipped together with Ruby, independent from the install path: [This commit](https://github.com/oneclick/rubyinstaller2/commit/21a416ffb73) should solve [this issue](https://github.com/oneclick/rubyinstaller/issues/172) and [this issue](https://github.com/oneclick/rubyinstaller/issues/285) and is described [here](https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-portable-install).
1. Removed some unecessary DLLs previously shipped with the installer: This shouldn't change anything visible, but [reduces the DLLs](https://github.com/oneclick/rubyinstaller2/commit/d39da51418a5b) to those that are really necessary for ruby core and stdlib. 
1. Decrease the number of MSYS2 packages installed per default using 'ridk install': We don't need all the previous installed MSYS2 development packages and use a reduced set now. This is only relevant for a fresh MSYS2 installation. It's [this commit](https://github.com/oneclick/rubyinstaller2/commit/0ebb396a89f12).

**Comment by Azolo** [comment]
@larskanis Nice, I really like the site. I remember discussing this in the past with @luislavena, I think even if he decides not to use GitHub Pages he will want to use the jekyll generated site.

Do you think the site should stay in the same repo or moved into a different repo?

**Comment by larskanis** [comment]
@Azolo My intention to place the web site into the rubyinstaller2 repo was to be able to add download links and a release post (at least a template) as part of a (future) release task. However this is not absolutely necessary - it's certainly possible to automate releases with a detached repo as well. For all I care it can be stay where it is, but it could also be extracted if there is some need or wish.

**Comment by johnnyshields** [comment]
@larskanis thanks for the top-notch work I and my team really appreciate it.

**Comment by larskanis** [comment]
Hi @luislavena ! Can you please find some time to make the RubyInstaller-2.4 release happen? I'm not sure how to proceed with the web site. If switching https://rubyinstaller.org to [the github hosted one](https://oneclick.github.io/rubyinstaller2/) is too difficult, we could use the current CMS and think about the static site later. Any chance?

**Comment by luislavena** [comment]
@larskanis perhaps will be good to split the website from the build process? That way the history of changes made to support RubyInstaller do not interfere with regular website maintenance.

**Comment by larskanis** [comment]
> perhaps will be good to split the website from the build process?

As explained in the above comments we can separate it into it's own repository. Shall I do it?

**Comment by luislavena** [comment]
re: dns switch, I think we can use github pages to host the site and continue to use cloudflare to provide the SSL layer:

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by luislavena** [comment]
> As explained in the above comments we can separate it into it's own repository. Shall I do it?

Please so, that will make things more easy to setup and others to contribute (aka: "**here** is the website vs the code)

**Comment by larskanis** [comment]
@luislavena  OK, looks good. I'm not familiar with cloudflare, but let me know, if I can do something.

**Comment by larskanis** [comment]
@luislavena I extracted the docs directory to https://github.com/oneclick/rubyinstaller.org-website (including it's history) and enabled the new github site: https://oneclick.github.io/rubyinstaller.org-website/

**Comment by luislavena** [comment]
@larskanis excellent. Thank you.

Can we make 2.4.1-1 a *draft* so we can do the DNS switch and check that everything continues to work?

**Comment by larskanis** [comment]
> Can we make 2.4.1-1 a draft so we can do the DNS switch and check that everything continues to work?

Done.

**Comment by luislavena** [comment]
@larskanis thank you!

Site is now run from the Jekyll website!!!

I've added `CNAME` and hide Ruby 2.4.1-1 release from downloads page. Setup Cloudflare and enforced HTTPS.

This should be good for a release and some proper announcement too!

**Comment by luislavena** [comment]
@larskanis 

I saw there were some attempts to compile Ruby 2.3 with the new repository (rubyinstaller2) but appears to be failing.

IMO I think 2.3 can still be solved by this repository and keep RI2 just for 2.4 and newer versions moving forward.

The only remaining change for this repo will be a warning/notice pointing to the new repository for those looking for Ruby 2.4.

Last but not least, there is a patch on the new installer that don't think is a good call to include (remember: RubyInstaller aimed to be as close as possible to upstream).

Let me know your thoughts.

Cheers.

**Comment by larskanis** [comment]
@luislavena Thanks for migrating the rubyinstaller website!

> I saw there were some attempts to compile Ruby 2.3 with the new repository (rubyinstaller2) but appears to be failing.

This "inofficial" - see https://github.com/oneclick/rubyinstaller2/issues/33

> The only remaining change for this repo will be a warning/notice pointing to the new repository for those looking for Ruby 2.4.

I agree. May I open a pull request?

> Last but not least, there is a patch on the new installer that don't think is a good call to include (remember: RubyInstaller aimed to be as close as possible to upstream).

To be honest, this was a no-brainer for me, but I was astounded how well `Encoding.default_external='locale'` seems to work for many people. This is not so in Europe, but I have to discuss that with the ruby core team. For the time being I [reverted this patch](faee37330315658f87a99a7d37928dc6c0ed35fd) and added it as an [installer option](35a7fce00f96c774b41c38e1424015e103c181b9). I also did some more work towards better Unicode/UTF-8 support on Windows which shall find it's way into future releases.

**Comment by luislavena** [comment]
@larskanis please, send a pull request for the README changes, thank you! :heart: :heart: :heart:

**Comment by larskanis** [comment]
RubyInstaller-2.4.1 is finally released and available on https://rubyinstaller.org !

@luislavena @Azolo I hope the [release text](https://github.com/oneclick/rubyinstaller.org-website/blob/master/_posts/2017-05-25-rubyinstaller-2.4.1-1-released.md) is OK for you. If not please change it! Can you furthermore post the news as done for earlier releases? Or tell me, where+how it used to be published?

**Comment by Azolo** [comment]
@larskanis I posted it to the [RubyInstaller Google Group][1], rubyinstaller.org, then put the release notes on Bintray.

I was posting to ruby-talk at one point, but stopped when keeping up with that mailing list became tedious.

[1]: https://groups.google.com/forum/#!forum/rubyinstaller

**Comment by Azolo** [comment]
For the release notes I would put something in big bold letters at the top that the DevKit for Ruby 2.4 is different than for previous releases.

Then also make click bait that's something like, "Download the DevKit for Ruby 2.4" that is a separate page that gives a walkthrough.

If you decide not to do that, it's still ok. That still won't be nearly enough for some people and you will get tons of bugs that the DevKit doesn't work. 😋 

Other than that it looks ok. Like 90% of the release notes that @luislavena and I did were notes about the DevKit or compiling gems. "Use this DevKit not that one.", "Not every Gem will be compiled.", or "Don't use Gems from previous releases." It probably helped a lot of people, but it never felt like it did.

**Comment by luislavena** [comment]
> RubyInstaller-2.4.1 is finally released and available on https://rubyinstaller.org !

Excellent work @larskanis !!! Thank you! ❤️ ❤️ ❤️ 

> I hope the release text is OK for you.

👍 

Originally I put lot of thoughts based on past releases and subsequent follow up with _why this doesn't work?_ and many other issues.

But even after putting those notes in the release announcement, nobody read them, and the questions kept coming.

I think a short announcement on RubyInstaller mailing list with the same release notes contents will be enough.

Thank you so much for stepping in and taking the lead for version 2.4, really really appreciate the effort you are making for all Ruby on Windows.

Cheers.

**Comment by ferventcoder** [comment]
Greetings all, I found one oddity with the new Ruby Installer - https://github.com/oneclick/rubyinstaller2/issues/43

It's not a blocker, more of an annoyance than anything else.

**Comment by larskanis** [comment]
I think this can finally be closed now.

Thank you to everyone how participated on this transition! Special thanks to @luislavena for getting https://github.com/oneclick/rubyinstaller.org-website up and running!
