### ISSUE TITLE
Ruby 1.8.7 - Could not find RubyGem cucumber (>= 0) (Gem::LoadError)

### ISSUE THREAD

**Issue by sanjayboa26** [oneclick/rubyinstaller#354]
Can you please let me know what is the issue
Operating system - windows 7
Ruby 1.8.7 
Gem version 1.5.2

C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:861:in `report_activate_error': Could not find RubyGem cucumber (>= 0) (Gem::LoadError)
                from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:255:in `activate'
                from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:1204:in `gem'
                from C:/Ruby187/bin/cucumber:18

**Comment by luislavena** [comment]
Ruby 1.8.7 has reached EOL (End Of Life) years ago.

Please upgrade to newer versions.
