### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by fengzhao** [oneclick/rubyinstaller#357]
Hi! Im trying setup rails on Windows 10.
and my ruby version is ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
and my ruby devkit version is  DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe

fengz@fengzhao-PC MINGW64 ~/Desktop/python练习/新建文件夹
$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]

fengz@fengzhao-PC MINGW64 ~/Desktop/python练习/新建文件夹
$ gem install rdiscount --platform=ruby
ERROR:  Error installing rdiscount:
        ERROR: Failed to build gem native extension.

  current directory: D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rdiscount-2.2.0.1/                                                                                                                                                                                               ext
D:/Ruby23-x64/bin/ruby.exe -r ./siteconf20170311-16004-garwk2.rb extconf.rb
checking for random()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/Ruby23-x64/bin/$(RUBY_BASE_NAME)
        --with-rdiscount-dir
        --without-rdiscount-dir
        --with-rdiscount-include
        --without-rdiscount-include=${rdiscount-dir}/include
        --with-rdiscount-lib
        --without-rdiscount-lib=${rdiscount-dir}/lib
D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to gen                                                                                                                                                                                               erate an executable file. (RuntimeError)
You have to install development tools first.
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:1051:in `block in have_func'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in po                                                                                                                                                                                               stpone'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from D:/Ruby23-x64/lib/ruby/2.3.0/mkmf.rb:1050:in `have_func'
        from extconf.rb:5:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can                                                                                                                                                                                                be found here:

  D:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/rdiscount-2.2.0                                                                                                                                                                                               .1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rdisco                                                                                                                                                                                               unt-2.2.0.1 for inspection.
Results logged to D:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0                                                                                                                                                                                               /rdiscount-2.2.0.1/gem_make.out
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...

fengz@fengzhao-PC MINGW64 ~/Desktop/python练习/新建文件夹
$

**Comment by vais** [comment]
Try running from a directory that does not have unicode characters in its name, maybe?
