### ISSUE TITLE
Ruby 2.4.1 released already. When RubyInstaller 2.4.1 will be released?

### ISSUE THREAD

**Issue by Sega100500** [oneclick/rubyinstaller#359]
Ruby 2.4.1 released already. When RubyInstaller 2.4.1 will be released?

**Comment by vais** [comment]
@Sega100500 https://github.com/larskanis/rubyinstaller2

**Comment by Sega100500** [comment]
There is pre-release.
When will be release?
Now  https://github.com/larskanis/rubyinstaller2 is official repo for http://rubyinstaller.org ?

**Comment by vais** [comment]
@Sega100500 no idea, it's up in the air now. My guess is not yet, but it looks like things are moving in that direction :man_shrugging:

**Comment by larskanis** [comment]
I uploaded a first release candidate: https://github.com/larskanis/rubyinstaller2/releases/tag/2.4.1-1rc1
You're welcome to try it out and give some feedback.

**Comment by luislavena** [comment]
There is no maintainer for this repository. Releases for 2.4.x are going to be handled by RubyInstaller2 repository.

A release candidate was made available: https://github.com/oneclick/rubyinstaller2/releases/tag/2.4.1-1rc1

Closing.
