### ISSUE TITLE
Ruby 2.3.4 released

### ISSUE THREAD

**Issue by ashmaroli** [oneclick/rubyinstaller#360]
Ruby 2.3.4 [released](https://www.ruby-lang.org/en/news/2017/03/30/ruby-2-3-4-released/) a few days back. Is a Windows Installer for this going to be released by this project or by RubyInstaller2?

Thanks to both projects either way :smiley: 

/cc @larskanis

**Comment by luislavena** [comment]
There is no maintainer for current rubyinstaller repository, which means most likely there will be no new 2.3.x release.

There are release candidates for 2.4.1 on rubyinstaller2.
