### ISSUE TITLE
Links to archived devkits broken

### ISSUE THREAD

**Issue by lbbethke** [oneclick/rubyinstaller#365]
I'm trying to download the 4.5.2 devkit as I need Ruby 1.8.7 on a project, but the links on the archive aren't working: https://rubyinstaller.org/downloads/archives/.

**Comment by larskanis** [comment]
Thanks for highlighting this! I've fixed the links: https://github.com/oneclick/rubyinstaller.org-website/commit/6a1d94e13326ef9fbdc3c9f347585f75aa2f1fc3

**Comment by lbbethke** [comment]
Great, thanks for fixing so quickly!
