### ISSUE TITLE
Can't correctly install 2.4.1-1-x64 with MSYS2 on Win10x64

### ISSUE THREAD

**Issue by the-nose-knows** [oneclick/rubyinstaller#366]
I attempted to transition from 2.2 to 2.4 and quickly install the `json` gem.

I was prompted to install MSYS2 and proceeded. About 66% through that install, an error `127` occurred when a bash-login was attempted. I tried to re-try but it never succeeded, so I skipped it and the installation completed without further issues, according to the MSYS2 status checks from my console output.

I just wanted to install Ruby and the JSON gem; that's all. I didn't have to deal with MSYS2 installations in 2.2.x, so I don't know if new precedents were set and not thoroughly communicated. Previously, I would install the RDK in-lieu of MSYS2. I saw no instructions to do this, so I did not.

I am on a proxy. I don't remember needing to do anything special to get gems installing, however.

```sh
C:\Ruby24-x64\bin>.\gem install json
Fetching: json-2.1.0.gem (100%)
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/

C:\Ruby24-x64\bin>ridk install
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 repository update
   3 - MSYS2 and MINGW development toolchain
Which components shall be installed? [1,2,3] 1

MSYS2 seems to be unavaiable
Verify integrity of msys2-x86_64-20161025.exe ... OK
Run the MSYS2 installer ...
> C:\Users\userName\AppData\Local\Temp/msys2-x86_64-20161025.exe
 Success

   1 - MSYS2 base installation
   2 - MSYS2 repository update
   3 - MSYS2 and MINGW development toolchain
Which components shall be installed? []

C:\Ruby24-x64\bin>.\gem install json
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170607-1540-zrptcx.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/json-2.1.0/gem_make.out

C:\Ruby24-x64\bin>ridk install
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 repository update
   3 - MSYS2 and MINGW development toolchain
Which components shall be installed? [1,2,3] 3

MSYS2 seems to be already installed
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autoconf2.13 autogen automake-wrapper automake1.10 automake1.11 automake1.12 automake1.13 automake1.14 automake1.15 automake1.6 automake1.7 automake1.8 automake1.9 diffutils file gawk grep libtool m4 make patch pkg-config sed texinfo texinfo-tex wget mingw-w64-x86_64-binutils mingw-w64-x86_64-crt-git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-headers-git mingw-w64-x86_64-libmangle-git mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-tools-git mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-winstorecompat-git
warning: file-5.28-2 is up to date -- skipping
warning: gawk-4.1.4-1 is up to date -- skipping
warning: grep-2.26-1 is up to date -- skipping
warning: m4-1.4.17-4 is up to date -- skipping
warning: sed-4.2.2-2 is up to date -- skipping
warning: wget-1.18-1 is up to date -- skipping
error: target not found: mingw-w64-x86_64-winstorecompat-git
Install MSYS2 and MINGW development toolchain failed
Installation failed: pacman failed

   1 - MSYS2 base installation
   2 - MSYS2 repository update
   3 - MSYS2 and MINGW development toolchain
Which components shall be installed? [] 2

MSYS2 seems to be already installed
MSYS2 repository update ...
> pacman -Sy --needed --noconfirm
:: Synchronizing package databases...
 mingw32                                          6.7 KiB   157K/s 00:00 [#######################################] 100%
 mingw32.sig                                      6.7 KiB   153K/s 00:00 [#######################################] 100%
error: GPGME error: No data
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
 mingw64                                          6.7 KiB   157K/s 00:00 [#######################################] 100%
 mingw64.sig                                      6.7 KiB   157K/s 00:00 [#######################################] 100%
error: GPGME error: No data
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
 msys                                             6.7 KiB   153K/s 00:00 [#######################################] 100%
 msys.sig                                         6.7 KiB   153K/s 00:00 [#######################################] 100%
error: GPGME error: No data
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize any databases
error: failed to init transaction (invalid or corrupted database (PGP signature))
MSYS2 repository update failed
Installation failed: pacman failed

   1 - MSYS2 base installation
   2 - MSYS2 repository update
   3 - MSYS2 and MINGW development toolchain
Which components shall be installed? [] 1

MSYS2 seems to be already installed

   1 - MSYS2 base installation
   2 - MSYS2 repository update
   3 - MSYS2 and MINGW development toolchain
Which components shall be installed? [] 3

MSYS2 seems to be already installed
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autoconf2.13 autogen automake-wrapper automake1.10 automake1.11 automake1.12 automake1.13 automake1.14 automake1.15 automake1.6 automake1.7 automake1.8 automake1.9 diffutils file gawk grep libtool m4 make patch pkg-config sed texinfo texinfo-tex wget mingw-w64-x86_64-binutils mingw-w64-x86_64-crt-git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-headers-git mingw-w64-x86_64-libmangle-git mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-tools-git mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-winstorecompat-git
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
Install MSYS2 and MINGW development toolchain failed
Installation failed: pacman failed

   1 - MSYS2 base installation
   2 - MSYS2 repository update
   3 - MSYS2 and MINGW development toolchain
Which components shall be installed? [] C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/ridk.rb:68:in `gets': Interrupt
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/ridk.rb:68:in `block in install'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/ridk.rb:62:in `loop'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/ridk.rb:62:in `install'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/ridk.rb:14:in `run!'
        from C:/Ruby24-x64/bin/ridk.cmd:32:in `<main>'
Terminate batch job (Y/N)? y

C:\Ruby24-x64\bin>
```

**Comment by Azolo** [comment]
Indeed things have changed, see this commit: 9bc32c35167abb2b75c8561b3794d1ce4012aa54, [the announcement on the website][announcement], and this blurb on the [downloads page][downloads]: 

> Ruby 2.4.0 and newer: The MSYS2 DevKit is downloaded as the last step of the installation.

That list isn't comprehensive, but @larskanis did try to communicate it. If there another outlet you can suggest we put this information we would certainly be open to doing so. We are desperately trying our best to avoid the confusion.

[announcement]: https://rubyinstaller.org/2017/05/25/rubyinstaller-2.4.1-1-released.html
[downloads]: https://rubyinstaller.org/downloads/

**Comment by seanvree** [comment]
Yeah, I'm having issues too.  although i finally got MAKE to work, I'm still having problems with ERROR CODE 2

```
C:\Ruby24-x64>ridk version
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-1
  git_commit: 6635d31
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev3, Built by MSYS2 project) 6.3.0
sh: GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)

C:\Ruby24-x64>ridk exec pacman -S mingw-w64-x86_64-sqlite3
resolving dependencies...
looking for conflicting packages...

Packages (8) mingw-w64-x86_64-expat-2.2.0-2  mingw-w64-x86_64-gettext-0.19.8.1-2
             mingw-w64-x86_64-libsystre-1.0.1-3  mingw-w64-x86_64-libtre-git-r128.6fb7206-1
             mingw-w64-x86_64-ncurses-6.0.20170325-1  mingw-w64-x86_64-readline-7.0.003-1
             mingw-w64-x86_64-termcap-1.3.1-2  mingw-w64-x86_64-sqlite3-3.18.0-1

Total Download Size:    6.11 MiB
Total Installed Size:  40.56 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 mingw-w64-x86_64-expat-2.2.0-2-any          120.3 KiB  1973K/s 00:00 [#####################################] 100%
 mingw-w64-x86_64-gettext-0.19.8.1-2-any       3.1 MiB  2.30M/s 00:01 [#####################################] 100%
 mingw-w64-x86_64-libtre-git-r128.6fb72...    82.1 KiB  11.5M/s 00:00 [#####################################] 100%
 mingw-w64-x86_64-libsystre-1.0.1-3-any       21.6 KiB  21.1M/s 00:00 [#####################################] 100%
 mingw-w64-x86_64-ncurses-6.0.20170325-...  1715.5 KiB  3.47M/s 00:00 [#####################################] 100%
 mingw-w64-x86_64-termcap-1.3.1-2-any         12.6 KiB  0.00B/s 00:00 [#####################################] 100%
 mingw-w64-x86_64-readline-7.0.003-1-any     353.4 KiB  4.79M/s 00:00 [#####################################] 100%
 mingw-w64-x86_64-sqlite3-3.18.0-1-any       746.7 KiB  3.70M/s 00:00 [#####################################] 100%
(8/8) checking keys in keyring                                        [#####################################] 100%
(8/8) checking package integrity                                      [#####################################] 100%
(8/8) loading package files                                           [#####################################] 100%
(8/8) checking for file conflicts                                     [#####################################] 100%
(8/8) checking available disk space                                   [#####################################] 100%
:: Processing package changes...
(1/8) installing mingw-w64-x86_64-expat                               [#####################################] 100%
(2/8) installing mingw-w64-x86_64-gettext                             [#####################################] 100%
(3/8) installing mingw-w64-x86_64-libtre-git                          [#####################################] 100%
(4/8) installing mingw-w64-x86_64-libsystre                           [#####################################] 100%
(5/8) installing mingw-w64-x86_64-ncurses                             [#####################################] 100%
(6/8) installing mingw-w64-x86_64-termcap                             [#####################################] 100%
(7/8) installing mingw-w64-x86_64-readline                            [#####################################] 100%
(8/8) installing mingw-w64-x86_64-sqlite3                             [#####################################] 100%

C:\Ruby24-x64>gem install sqlite3 --platform ruby
Fetching: sqlite3-1.3.13.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13/ext/sqlite3
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170602-1448-2q2cyo.rb extconf.rb
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... yes
checking for rb_integer_pack()... yes
checking for sqlite3_initialize()... yes
checking for sqlite3_backup_init()... yes
checking for sqlite3_column_database_name()... yes
checking for sqlite3_enable_load_extension()... yes
checking for sqlite3_load_extension()... yes
checking for sqlite3_open_v2()... yes
checking for sqlite3_prepare_v2()... yes
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13/ext/sqlite3
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13/ext/sqlite3
make "DESTDIR="
generating sqlite3_native-x64-mingw32.def
make: *** No rule to make target '/C/Ruby24-x64/include/ruby-2.4.0/ruby.h', needed by 'backup.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/sqlite3-1.3.13/gem_make.out

C:\Ruby24-x64>
```

**Comment by Azolo** [comment]
@seanvree That is actually again seems to be a communication issue. See [RubyInstaller2 - Gems With Additional Library Dependencies][1].

[1]: https://github.com/oneclick/rubyinstaller2#install-gems-with-c-extensions-and-additional-library-dependencies

**Comment by seanvree** [comment]
@Azolo  - you mean a WAN connection issue?

**Comment by Azolo** [comment]
@seanvree Ahh, I see. You did install sqlite3 libs. It appears that there's something else wrong with your environment but it doesn't appear to be a connection issue for you.

I would suggest opening an issue on the RubyInstaller2 repo.

**Comment by seanvree** [comment]
Yeah, I can install Sqlite3 fine.  

Will do. thanks!

**Comment by the-nose-knows** [comment]
@Azolo allow me a moment to clarify one thing before proceeding. The requirement for MSYS2 was communicated via the installer. It was the discontinuation of the RDK that I didn't notice.

My issue remains however. I don't know why my installation is not working. What do I need to do? I don't know what the core issue is besides what the console provided.

**Comment by dmajkic** [comment]
@the-nose-knows it looks like you have existing MSYS2 installation with some internal errors.
Eg. look at these lines from your log:

> error: GPGME error: No data
> error: failed to update msys (invalid or corrupted database (PGP signature))
> error: failed to synchronize any databases
> error: failed to init transaction (invalid or corrupted database (PGP signature))

You should try to reinstall msys2, or fix installation. This is something MSYS2 related, you should try to ask them if there is a way to fix this. If you decide to reinstall, check if previous installation was used for something else.

**Comment by the-nose-knows** [comment]
I uninstalled MSYS2 and installed it directly from MSYS2's site. I now have different errors...

Are you sure I'm not missing a link to help finish correct installation or something? Because if it's complaining missing headers then the compiler flags or the environment is likely not being correctly loaded.

```sh
COMPNAME+UserName@CompName  /c/Ruby24-x64/bin
$ gem install json
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170609-12424-1v2ceqg.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
generating generator-x64-mingw32.def
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h:5:18: fatal error: ruby.h: No such file or directory
compilation terminated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/json-2.1.0/gem_make.out
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...

COMPNAME+UserName@CompName  /c/Ruby24-x64/bin
$

```

I even put `C:\Ruby24-x64\include\ruby-2.4.0` in my `PATH` where that header is! So I don't know what kind of non-sense is happening... Not going to lie; this is really frustrating. Any pertinent info you can share will be appreciated.

**Comment by dmajkic** [comment]
@the-nose-knows  Did you try to run `C:\gem install json` eg. from Windows command prompt (cmd.exe), not from msys bash?

**Comment by seanvree** [comment]
FYI:  This is happening for me on Rubyinstaller2 as well.  I'd appreciate some input!

https://github.com/oneclick/rubyinstaller2/issues/47

**Comment by seanvree** [comment]
Any work being done on this by chance?

**Comment by Azolo** [comment]
This would be handled in the RubyInstaller2 repo. Closing to direct any conversation there.

**Comment by victorhantelmann** [comment]
<code>pacman -Sy pacman</code> to solve it

**Comment by seanvree** [comment]
@victorhantelmann  - 

I get "no display possible" when I run that command.

**Comment by gavvvr** [comment]
```
warning: wget-1.18-1 is up to date -- skipping
error: target not found: mingw-w64-x86_64-winstorecompat-git
Install MSYS2 and MINGW development toolchain failed
Installation failed: pacman failed
```

I was able to fix this by running `pacman -Syy` manually.

**Comment by cdenneen** [comment]
From a fresh install this is broken until you manually run `pacman -Sy pacman` or the latter.
And this is with the latest version `2.4.1-2-x86`
I'm not sure this issue is closed. Can someone please reopen?

**Comment by MalekMFS** [comment]
Solved. Caused communication problem(my custom firewall blocked `pacman`)
Note i am talking about `ridk install` then `3 - MSYS2 and MINGW development toolchain`

**Comment by friek108** [comment]
If I run `pacman -Syy` on the command line, it says pacman is not recognized as an internal or external command. Can you provide some more info on how to get this to work? I've disabled my firewall, antivirus and tried using both 32 and 64 bit, keep getting the same error `failed installation failed: pacman failed`. Using the latest `rubyinstaller-2.4.2-2-x64.exe` installer

**Comment by MSP-Greg** [comment]
Normally, you would run pacman commands in the MSYS2 bash shell.

If MSYS2 is installed, you should have shortcuts, otherwise, I believe on a normal 64 bit system, the bash shell launches with:

```
C:\msys64\msys2_shell.cmd -mingw64
```
Once that opens, you can enter pacman commands.  Note that since it's a bash shell, insert/paste is Shift-Insert

**Comment by larskanis** [comment]
@friek108 In addition to the MSYS2 shell as described by @MSP-Greg there are several convenience methods in RubyInstaller-2.4:

`ridk install 2` runs the two pacman commands which are needed to update the MSYS2 system. So you don't have to run the pacman commands manually.

`ridk enable` enables MSYS2 commands within the cmd shell or in PowerShell. You can then run `pacman -Syy` or so without a MSYS2/bash shell.

`ridk exec pacman ...` executes one single MSYS2 command in cmd or PowerShell.

Please open a new github issue if you still have problems with your RubyInstaller setup.

**Comment by dtasev** [comment]
I had a similar issue, failing on the `pacman`, step 2. I *did not* have a manual mingw install.
However, the `ridk install` was picking up a `mingw` installation! This turned out to be a mingw distributed by the Windows Git installation.

I figured that out after a `ridk enable` added `C:\Program Files\Git\mingw\bin` to the `PATH`. This happened because I had `C:\Program Files\Git` in my path. After removing it, `ridk install` correctly picks up that **no mingw exists** and now it is installing everything correctly.

I do not know if the mingw distributed with Git can be used, as it seems to be lacking some tools.

**Comment by seanstr** [comment]
Similar to DTasev I had C:\Program Files\Git\cmd in my path, and once I removed that it installed mingw and properly ran the make to create native gems

**Comment by Juksefantomet** [comment]
So i ended up with the pacman issue in relation with failing to bundle install nio4r gem on win10 (2.5.0 ruby, 2.4.0 devkit both 64-bit)

Following default ridk install it fails as previous posts. My solution was removing the 

 --noconfirm  from the `pacman -Syu --needed --noconfirm`

Giving me this output:

*NOTE: i had no issues removing those libs, but i've not tested what they actually affect, but as i have minimal ruby-related stuff installed on my computer or otherwise related to development i could remove those without considering side-effects.

i wanted to post this so you guys can investigate this further and figure out why and what those conflicting libs are but they are the reason pacman failed on the auto-deploy on my end.

MSYS264 output:

`pacman -Syu --needed
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...
:: msys2-runtime and catgets are in conflict. Remove catgets? [y/N] y
:: msys2-runtime and libcatgets are in conflict. Remove libcatgets? [y/N] y

Packages (7) bash-4.4.019-2  catgets-1.1-2 [removal]  filesystem-2018.02-2
             libcatgets-1.1-2 [removal]  mintty-1~2.8.4-1
             msys2-runtime-2.10.0-2  pacman-5.0.1-5

Total Download Size:   11.68 MiB
Total Installed Size:  56.27 MiB
Net Upgrade Size:       4.59 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 msys2-runtime-2.10....     2.5 MiB  1173K/s 00:02 [#####################] 100%
 bash-4.4.019-2-x86_64   1978.4 KiB  1429K/s 00:01 [#####################] 100%
 filesystem-2018.02-...    41.9 KiB  41.0M/s 00:00 [#####################] 100%
 mintty-1~2.8.4-1-x86_64  249.9 KiB  1612K/s 00:00 [#####################] 100%
 pacman-5.0.1-5-x86_64      7.0 MiB  1375K/s 00:05 [#####################] 100%
(5/5) checking keys in keyring                     [#####################] 100%
(5/5) checking package integrity                   [#####################] 100%
(5/5) loading package files                        [#####################] 100%
(5/5) checking for file conflicts                  [#####################] 100%
(7/7) checking available disk space                [#####################] 100%
warning: could not get file information for home/
warning: could not get file information for opt/
:: Processing package changes...
(1/2) removing catgets                             [#####################] 100%
(2/2) removing libcatgets                          [#####################] 100%
(1/5) upgrading msys2-runtime                      [#####################] 100%
(2/5) upgrading bash                               [#####################] 100%
(3/5) upgrading filesystem                         [#####################] 100%
(4/5) upgrading mintty                             [#####################] 100%
(5/5) upgrading pacman                             [#####################] 100%
warning: terminate MSYS2 without returning to shell and check for updates again
warning: for example close your terminal window instead of calling exit`

Once this was completed i re-rean `ridk install` and it ran through eventually allowing me to run

`gem install nio4r -v '2.3.0'`

Hope this helped!

**Comment by larskanis** [comment]
@Juksefantomet Sorry for the inconvenience! However the issue with conflicting catget packages was solved by a [new RubyInstaller release](https://rubyinstaller.org/2018/02/27/rubyinstaller-2.5.0-2-and-2.4.3-2-released.html). Updating and running `ridk install` once should fix gem installation as well.
