### ISSUE TITLE
What is the correct way to install required dependency to build gem in RubyInstaller2?

### ISSUE THREAD

**Issue by tfaruq** [oneclick/rubyinstaller#367]
I just install and download the latest Ruby 2.4.1-1 (x64) installer. When I run `gem update`, some of gem failed to update due to build error. Then I run mysys-64:
`pacman -Sy`
`pacman -S --needed base-devel`
`pacman -S mingw-w64-x86_64-gcc`
`pacman -S mingw-w64-x86_64-cmake`

Re-run  `gem update` is successful now. Is this the proper way to do?

**Comment by larskanis** [comment]
`ridk install` should install required MSYS2 and MINGW packages.

**Comment by tfaruq** [comment]
Ok thank you so much!!
