### ISSUE TITLE
Check for bash configuration files before overwriting!

### ISSUE THREAD

**Issue by mcandre** [oneclick/rubyinstaller#368]
Ay, in the event that the user already has his own custom ~/.bash_profile, ~/.bashrc, etc., ask before overwriting these when installing Ruby. It stinks to lose these settings!

At the very least, append to these files, rather than replacing them.

**Comment by larskanis** [comment]
RubyInstaller doesn't modify any bash config files. What's the content of the new files? Possibly this gives an indication where the modification Congress from.

**Comment by larskanis** [comment]
Closing because of no response.

**Comment by mcandre** [comment]
rubyinstaller does overwrite bash config files, e.g. in Git Bash, without bothering to ask the user first.
