### ISSUE TITLE
2.4 installer and Ruby-Tk

### ISSUE THREAD

**Issue by jamgard** [oneclick/rubyinstaller#371]
Does not install Ruby-Tk or give an option to do so

**Comment by larskanis** [comment]
tk was removed from ruby-2.4 stdlibs but is still available as a gem. Use:
```sh
ridk exec pacman -S mingw-w64-x86_64-tk
gem install tk
```

I just opened [a pull request](https://github.com/ruby/tk/pull/10) which will automatically issue the pacman command while gem install in the future.

**Comment by larskanis** [comment]
The tk gem auto-installs the tk-package now: https://github.com/ruby/tk/pull/10#issuecomment-319263301
