### ISSUE TITLE
Packman.exe came through with the download

### ISSUE THREAD

**Issue by dupls** [oneclick/rubyinstaller#377]
I downloaded rubyinstaller-2.4.1-2-x86 and checked the box for additional components to be installed. My virus protector popped up preventing packman.exe being installed on my computer. I removed the folder and tried the same installer again this time without checking the box for additional components. Ruby installer downloaded without problems. 
To confirm I have ruby 2.4.1p111 (2017-03-22 revision 58053 [i386-mingw32]

**Comment by larskanis** [comment]
Can you please open a new issue in the project https://github.com/oneclick/rubyinstaller2 ? This is where RubyInstaller-2.4 is managed.

Also please describe what your expectation is and what you think should be improved.

**Comment by dupls** [comment]
Super I have, you can remove this here if you like
