### ISSUE TITLE
how to add bundles actually i am making new dashing file after that what should i do??

### ISSUE THREAD

**Issue by deepalityagi00** [oneclick/rubyinstaller#379]
**NOTE**: This project is for Ruby version 2.3 and older.
For Ruby versions >= 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller2/issues/new ).

## after this all the create files are added to it but no information for bundles and if i execute "bundles" it shows error

[](url)

**Comment by larskanis** [comment]
To be able to help you, we need a minimum of information:

What problems are you experiencing?
Steps to reproduce
What's the output from `ruby -v`?

**Comment by deepalityagi00** [comment]
The problem occurs when i am trying to point the browser at local host by using the command 
> dashing start -p 8080
on ruby and then opening the browser at https://localhost:8080
 The output on the ruby >Invalid request:Invalid HTTP format,parsing format.
Please can you tell me how to tune the browser at localhost8080

**Comment by larskanis** [comment]
Did you try http://localhost:8080 (without SSL)?
Anyway please ask the people at  http://dashing.io/ for further help. This project it's about ruby core implementation only.

**Comment by deepalityagi00** [comment]
yes i tried but  8080. but nothing happens and it shoes the error that the
site is unreachable . what should i do.
