### ISSUE TITLE
error in setting up

### ISSUE THREAD

**Issue by thornbirda** [oneclick/rubyinstaller#380]
**NOTE**: This project is for Ruby version 2.3 and older.
For Ruby versions >= 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller2/issues/new ).

## What problems are you experiencing?
I got a problem as like following errors. What do I do to solve this.
os: win10

C:\Users\sm>irb
C:/aa/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:652:in `encode': incomplete "\x00" on UTF-16LE (Encoding::InvalidByteSequenceError)
        from C:/aa/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:652:in `read'
        from C:/aa/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:680:in `[]'
        from C:/aa/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:51:in `block (2 levels) in iterate_msys_paths'
        from C:/aa/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:612:in `each_key'
        from C:/aa/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:49:in `block in iterate_msys_paths'
        from C:/aa/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        from C:/aa/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        from C:/aa/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:48:in `iterate_msys_paths'
        from C:/aa/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:69:in `msys_path'
        from C:/aa/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:82:in `mingw_bin_path'
        from C:/aa/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:92:in `enable_dll_search_paths'
        from C:/aa/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
        from C:/aa/Ruby24-x64/lib/ruby/2.4.0/rubygems/defaults/operating_system.rb:3:in `<top (required)>'
        from C:/aa/Ruby24-x64/lib/ruby/2.4.0/rubygems.rb:1346:in `require'
        from C:/aa/Ruby24-x64/lib/ruby/2.4.0/rubygems.rb:1346:in `<top (required)>'
        from <internal:gem_prelude>:4:in `require'
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

**Comment by larskanis** [comment]
Closing in favor of https://github.com/oneclick/rubyinstaller2/issues/86
