### ISSUE TITLE
RubyInstaller1 based installer for ruby2.3.5 is available, help needed to know if this can be contributed to this community

### ISSUE THREAD

**Issue by Sneha-Deshpande-9389** [oneclick/rubyinstaller#382]
Hi, I have built a rubyInstaller based rubyInstaller.exe for ruby 2.3.5 and I would like to contribute the same to oneclick rubyinstaller.  
Can you please help me with the steps to follow to upload the package to bintray?

**Comment by Sneha-Deshpande-9389** [comment]
Any updates?

**Comment by larskanis** [comment]
Feel free to upload your binaries to your bintray account and post a link here. Maybe someone is daring enough to execute code from totally untrusted sources, but I'll not make any such binary files to our official release.

You could open a pull request to this repository, which updates to the latest ruby versions and fixes outstanding issues. But to be honest, it's probably a better investment, to make the gems and applications you care about compatible to RubyInstaller-2.4+.

**Comment by Sneha-Deshpande-9389** [comment]
I have uploaded the rubyInstaller here: https://bintray.com/snehaorg/ruby2.3.5/2.3.5/1.0#files

**Comment by luislavena** [comment]
Hello,

As responded by Lars, RubyInstaller cannot accept binaries from 3rd parties.

If you want to contribute to the project, I suggest you take a look to the open [*Looking for Maintainers*](https://github.com/oneclick/rubyinstaller/issues/348#issuecomment-265838425) issue, specifically the comment I linked, which includes instructions on getting things running locally.

Perhaps you can introduce these modifications to the repository and send a Pull Request.

Hope that helps.

Cheers.
