### ISSUE TITLE
Wrong Version of Ruby for Windows gets installed from install package

### ISSUE THREAD

**Issue by ghost** [oneclick/rubyinstaller#384]
**NOTE**: This project is for Ruby version 2.3 and older.
For Ruby versions >= 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller2/issues/new ).

## What problems are you experiencing?
The wrong version of Ruby gets installed from the package I get [at](https://rubyinstaller.org/downloads/)
I selected and installed 

## Steps to reproduce
I selected and installed Ruby 2.4.3-2 (x64)  and ran the installation.    But I get a different version installed.

## What's the output from `ruby -v`?

C:\Users\Bill Cory>ruby --version
ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

C:\Users\Bill Cory>ruby -v
ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

**Comment by larskanis** [comment]
The version of ruby, which is used by the command line, is determined by the PATH environment variable. You should go into system settings -> environment variables and check which version of ruby comes first in the list of paths.

**Comment by larskanis** [comment]
Please also note, that changes to environment variables get effective only, if you open a new command prompt from the start menu.

**Comment by ghost** [comment]
![snap1](https://user-images.githubusercontent.com/3368373/38121815-c2944742-338e-11e8-8d55-ff2fd1a68459.jpg)
 I don't see ruby mentioned?

**Comment by MSP-Greg** [comment]
At a command prompt, type `PATH`, that will show your path.  I'm on Win7, I assume that 'Browse' might show a list of current system variables...

**Comment by ghost** [comment]
This is what I get: 
ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

C:\Users\Bill Cory>PATH
PATH=C:\Ruby22-x64\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Amazon\AWSCLI\;C:\Program Files\nodejs\;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Skype\Phone\;C:\Users\Bill Cory\AppData\Local\Microsoft\WindowsApps;C:\Users\Bill Cory\AppData\Roaming\npm;C:\hugo\bin

C:\Users\Bill Cory>

**Comment by ghost** [comment]
How do I change the path to:   Ruby24-x64 or Ruby25-x64

**Comment by MSP-Greg** [comment]
I've got a different dialog box in Win7.  What happens if you click 'Browse...'?

**Comment by ghost** [comment]
I did this;
C:\Users\Bill Cory>cd ..

C:\Users>cd ..

C:\>cd Ruby24-x64

C:\Ruby24-x64>

But how can I set this up so it defaults to this...if this is where it should be.

**Comment by ghost** [comment]
C:\Ruby24-x64>browse
'browse' is not recognized as an internal or external command,
operable program or batch file.

C:\Ruby24-x64>

**Comment by MSP-Greg** [comment]
I'm sorry.  In this thread you posted a screen grab of a window titled 'Edit environment variable'.  Click browse there.

**Comment by ghost** [comment]
Oh,   Here is what I did: 
![image](https://user-images.githubusercontent.com/3368373/38122576-247a89e0-3393-11e8-8ea4-78039c3a94ba.png)

**Comment by ghost** [comment]
When I close and reopen the Ruby start command prompt it opens the Ruby 2.2 version even after making the above change?

**Comment by MSP-Greg** [comment]
Ok.  As I mentioned, I'm using Win7, and my windows/dialogs for environment variables are different.

The `PATH` variable defines where your system looks for commands / *.exe files that are entered/called  without a full path.  It is a list of folders/directories, separated by semi-colons `;`.  For Ruby, regardless of the version, it must be to the bin folder, like `C:\Ruby24-x64\bin` or `C:\Ruby25-x64\bin`.

**Comment by ghost** [comment]
Here are my paths:

![image](https://user-images.githubusercontent.com/3368373/38122873-fe7ce13c-3394-11e8-908d-6e97ff69ad38.png)

**Comment by MSP-Greg** [comment]
That should work, I'm assuming Ruby isn't in your System variable `PATH`.  Open a new command window, and you should be running Ruby 2.4

**Comment by ghost** [comment]
The ruby cmd still brings up the Ruby 2.2
 I don't know what you mean by Ruby isn't in your Systems variable PATH

**Comment by ghost** [comment]
Here's my systems variables:
![image](https://user-images.githubusercontent.com/3368373/38123063-4bbaa6ae-3396-11e8-9187-40d232d8b461.png)

**Comment by MSP-Greg** [comment]
In your post that started with 'Here are my paths:' there are two lists, one is user, one is system.  System `PATH` is wider than the window, so I can't see what the full folder list is.

I might suggest removing Ruby from your user PATH and adding it to you system PATH.

**Comment by ghost** [comment]
**_"I might suggest removing Ruby from you user PATH and adding it to you system PATH."_**  I tried this also.  Before going any further here is a jpg of my C: drive and location of Ruby 2.4

![image](https://user-images.githubusercontent.com/3368373/38123553-e789278e-3398-11e8-8ec5-3055d506dcff.png)

**Comment by ghost** [comment]
Maybe if I uninstall Ruby 22-x64....after all I don't plan on ever using it.    Or unistall them all and then reinstall Ruby 24-x64 the cmd will default to 24-x64....?

**Comment by MSP-Greg** [comment]
Not required.  You need to get your path sorted out.  As I mentioned, remove Ruby from your user path, and add it to your system path.  You'll probably need to open a new command window after you've made the changes.

Since the system path string is often wider than the window, I copy and paste it into a text editor where horizontal scrolling is (hopefully) easier.

I'm AFK soon...

**Comment by ghost** [comment]
Ok,   I'll work on it.   Thanks for you help.   One more question.    I could just cd to Ruby24/bin from the cmd and install Middleman.     Maybe that's what I will do.

**Comment by ghost** [comment]
I gave up on installing middleman on my Windows 10 machine.
**This was my last command and I don't have a clue what went wron**g:
**PS C:\Ruby24-x64> middleman init test1**
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions/rendering.rb:11:in `block in <top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:91:in `load'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:127:in `block in load_settings'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:125:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:125:in `load_settings'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/extension_manager.rb:12:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:263:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:263:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `<top (required)>'
        from C:/Ruby24-x64/bin/middleman:23:in `load'
        from C:/Ruby24-x64/bin/middleman:23:in `<main>'

**Comment by MSP-Greg** [comment]
Re your middleman issue, I suspect both your js runtime and ruby should be in your PATH.  You might google:
Windows 10 add folder to PATH
First link I saw there was:
http://www.itprotoday.com/management-mobility/how-can-i-add-new-folder-my-system-path

You need to understand what `PATH` does and how to change it.  If you're using windows,  a basic understanding of cmd and ps1 files (command & PowerShell script files) would also be helpful.

**Comment by luislavena** [comment]
@FodorTheMagnificent have you solved the original issue reported here? Did you discover how that other version of Ruby was installed and able to uninstall it?

For the record, you can always run `where ruby.exe` in the command line and will tell you which directory that Ruby executable is coming from.

In relation to your middleman issue, it appears to be associated with execjs and not able to find Windows default JavaScript runtime.

On Windows 10, JScript might no longer be present, in which case, is recommended you install any of NodeJS LTS versions.

Hope that information helps and you can solve your problem.

Please let us know so we can close this issue.

Cheers.

**Comment by luislavena** [comment]
Hello @FodorTheMagnificent, closing this due stale (no response) from your end and also a duplicate from another issue reported in RubyInstaller2 repository (https://github.com/oneclick/rubyinstaller2/issues/109)

Please let us know if you solved that issue and if not, please use the relevant RubyInstaller2 issue linked above.

Cheers.
