### ISSUE TITLE
ruby  loadError: 126 cannot found module

### ISSUE THREAD

**Issue by LItterBoy-GB** [oneclick/rubyinstaller#386]
**NOTE**: This project is for Ruby version 2.3 and older.
For Ruby versions >= 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller2/issues/new ).

## What problems are you experiencing?
I complied the ruby.And I require "xxx.so". faild
But I use the ruby(https://rubyinstaller.org/ download) to requeire ’xxx.so‘ , success.

## Steps to reproduce
rake ruby22 DKVER=mingw64-64-4.7.2

## What's the output from `ruby -v`?
ruby(https://rubyinstaller.org/ download) 
      ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
ruby(I complied)
      ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
![111](https://user-images.githubusercontent.com/28385638/38540213-bec60040-3ccd-11e8-97a8-00fef0a07b2e.jpg)
## update image
![20180412142134](https://user-images.githubusercontent.com/28385638/38659961-37a9f78c-3e5e-11e8-9c1f-fb9a6d77a62a.jpg)

**Comment by LItterBoy-GB** [comment]
![qq 20180410143033](https://user-images.githubusercontent.com/28385638/38540531-cb416a8e-3cce-11e8-920f-f37f7cd5f350.jpg)

**Comment by LItterBoy-GB** [comment]
@wayneeseguin @vertiginous @luislavena @rdp @voxik  help me.

**Comment by dmajkic** [comment]
On your pictures, the ruby on the left one is **ruby 2.4.3p205**  and right one is **ruby 2.2.4p230**

I guess that 2.4 and 2.2 are not binary compatible, or probably your **f:/clipper.so** extension is for **2.2**

**Comment by LItterBoy-GB** [comment]
@dmajkic  sorry, It is my fault。 Because my compute install ruby2.4.  I update the image.
![20180412142134](https://user-images.githubusercontent.com/28385638/38659690-1fab3d86-3e5d-11e8-975c-9354b8bd3a6d.jpg)

**Comment by dmajkic** [comment]
What is the translation after "LoadError: 193: %1 ..." ?

**Comment by LItterBoy-GB** [comment]
@dmajkic  not a valid win32 application

**Comment by dmajkic** [comment]
@LItterBoy-GB  What does RUBY_PLATFORM say ?

**Comment by LItterBoy-GB** [comment]
@dmajkic  **x64-mingw32**

**Comment by dmajkic** [comment]
I am out of ideas. It looks like issue specific to clipper.so. Did you check what dlls does it require, and if they are accessible from ruby environment? Try also with removing ruby 2.4 from path before using your sandoxed ruby 2.2.

**Comment by LItterBoy-GB** [comment]
@dmajkic  The step of complie 64bit ("rake ruby22 DKVER=mingw64-64-4.7.2")  is ok?
Thank You!

**Comment by LItterBoy-GB** [comment]
@dmajkic

**Comment by luislavena** [comment]
@LItterBoy-GB `LoadError 193` is a common error received when attempting to load a DLL (`clipper.so`) and it fails to load the associated dependencies.

Please note that while you have Ruby in the sandbox environment, that doesn't mean that Ruby is within the `PATH`. From the screenshots I can see you `cd`ed into `bin` directory, which differs from having Ruby installed.

Perhaps `clipper.so` is depending on some DLLs are that found in Ruby bin directory, or maybe other places.

First thing I would try will be adjust the `PATH` of your local prompt to give priority to the sandboxed Ruby and try load the extension again, example:

```console
C:\>SET PATH=C:\Path\To\sandbox\ruby22_mingw\bin;%PATH%

C:\>where ruby.exe
C:\>where irb
# confirm here in the output that right Ruby is being used

C:\>irb
# try to load clipper.so
```

I will recommend using [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) in the computer that the project works to determine any DLL dependencies that `clipper.so` is trying to load that are not globally available.

Simply fire the working irb, load `clipper.so` and then inspect with Process Explorer.

It might also be possible that your Ruby 2.2 installation contains other DLLs that are not part of the standard Ruby 2.2 install, in which case using Process Explorer will help you debug.

Other alternative will be the usage of [Dependency Walker](http://www.dependencywalker.com/)

Hope that information helps. Please let us know your results.

Cheers.

**Comment by LItterBoy-GB** [comment]
@luislavena  Thank you. "clipper.so" has no other dependence. I guess less things, but I don't know what less. The logs of complied is ok. How can I find it.
![8](https://user-images.githubusercontent.com/28385638/39078788-41ff9fcc-4541-11e8-921a-b3d7e4b27cb9.jpg)

**Comment by luislavena** [comment]
Please read my message carefully since it contains instructions to detect
dependencies at runtime. clipper.so is a dll, so you need to load the
working Ruby and inspect with process explorer.

What you sent in the screenshots is irrelevant to what I have asked before.

Sorry for to posting. Sent from mobile.

**Comment by LItterBoy-GB** [comment]
@luislavena   I can not find anything of different dependencies. The step (get 64bit) is "rake ruby22 DKVER=mingw64-64-4.7.2". Is ok the step?
![image](https://user-images.githubusercontent.com/28385638/39079429-134beab2-454d-11e8-90df-99a52525025d.png)
![qq 20180421094142](https://user-images.githubusercontent.com/28385638/39079432-16071b32-454d-11e8-9733-bc940a7c2fd5.jpg)

**Comment by LItterBoy-GB** [comment]
@luislavena   I find why.  The dll is 32bit. But I run 'rake ruby22 DKVER=mingw64-64-4.7.2'.
![image](https://user-images.githubusercontent.com/28385638/39079770-c2485824-4553-11e8-8044-2a1fcac8bca5.png)
How can I get ruby_64bit?

**Comment by luislavena** [comment]
If dll is 32bits you need to build 32bits Ruby. See readme instructions to
use other devkit compatible.

If not, you need to obtain a 64bits version of the dll.

That is beyond the scope of this project.

Sorry for to posting. Sent from mobile.

**Comment by luislavena** [comment]
Also, it appears you have ignored what I recommended you to do, which is
use process explorer to inspect loaded dll from the working installation.

Please do that before anything else.

Will not respond further until you have followed instructions from previous
comments on that and change of path to test dependencies.

Sorry for to posting. Sent from mobile.

**Comment by LItterBoy-GB** [comment]
@luislavena sorry, I don't know how to use this tool(process explorer). So I use vs to debug it.
This project can not build 64bit ruby?
The command “rake ruby22 DKVER=mingw64-64-4.7.2” can't build 64bit ruby.

**Comment by LItterBoy-GB** [comment]
@luislavena @dmajkic 
I find why. 
Beacuse I complie 32bit ruby , then I don't delete the 32bit libs in sandbox.
When I complie 64bit ruby, the compiler use the 32bit lib in sandbox.
Thank you every one that help me.

**Comment by luislavena** [comment]
> The command “rake ruby22 DKVER=mingw64-64-4.7.2” can't build 64bit ruby.

If you build the 32bits version at some point, you need to remove the sandbox and compile again. That is an issue of current recipes.

Happy to hear you solved it.

Cheers.
