### ISSUE TITLE
Wiki - Development Kit - Installation Instructions - Testing Installation :: Correction

### ISSUE THREAD

**Issue by rjshaver** [oneclick/rubyinstaller#388]
While reading over your documentation in the Wiki, I used the section of the Installation Instructions - 5. Testing Installation to check a previous installation of Ruby.  I found that one command would not run and I had to make a change in the command.  This is after the installation of json, I ran the command starting 'ruby -rubygems ...' but it did not work on my machine.  By altering the command to 
'ruby -rrubygems ...', the command worked correctly.  

I cloned the wiki, forked rubyinstaller and pushed it up to my fork, but never found a way to send a pull request to the onclick/rubyinstaller.  My fork is [https://github.com/rjshaver/rubyinstaller](https://github.com/rjshaver/rubyinstaller).  I tried putting it into another branch but that does not seem to work with the wiki either.  I tried to make it easy for you, but this is so simple, it may be easier for you to just find the difference and change on your copy.

*

**Comment by rjshaver** [comment]
I did not see where I could edit the wikipage on the oneclick/rubyinstaller before, but I changed it.  I see the altered wiki page Development Kit, but maybe you will need to accept it.  Thanks.

**Comment by MSP-Greg** [comment]
@rjshaver

I haven't gone crazy looking, but generally, `ruby -rubygems` only fails on Ruby 2.5 or later.  What version of Ruby are you running, (`ruby -v`)?

**Comment by rjshaver** [comment]
Yes, it is Ruby 2.5.1.  I set that up a month or more ago, but may have updated last night.  That would be the reason.  Thanks for the quick feedback.

**Comment by MSP-Greg** [comment]
Ok.  Just to clarify, this repo is for Ruby versions 2.3 and lower, [RubyInstaller2](https://github.com/oneclick/rubyinstaller2) is for Ruby 2.4 and later.

Re RubyGems, a long time ago someone thought it looked odd to type `-rrubygems`, so they added what one might call an alias to `rubygems.rb` from a file named `ubygems.rb` (which allowed one to type `-rubygems`).  I think it got yanked out before Ruby 2.5 was released, but has been added back in to RubyGems updates.

So, if you update to RubyGems 2.7.7, you should have it back.  Greg

**Comment by rjshaver** [comment]
Ok.  Yes, I am new to Ruby and did not see the difference in installers.  I did see finally see where the rubyinstaller is used for 2.3 and before and rubyinstaller2 in 2.4 and above in a youtube video.   Thanks for the heads-up and background info.  Thanks for your time.

**Comment by luislavena** [comment]
Hello @rjshaver, thank you for the updates to the Wiki. 

Closing this now.
