### ISSUE TITLE
Sunsetting Amazon Web Services connected with RubyInstaller

### ISSUE THREAD

**Issue by luislavena** [oneclick/rubyinstaller#391]
Hello folks,

Been providing S3 and CloudFront setup for RubyInstaller since November 2008.

Originally this was the source of the downloads provided by the website, and also served the JS/CSS of the initial website build.

I've been paying these expenses without issues, but now that I've been away of the project for more than 3 years, I think is time to sunset those expenses.

While not prohibited expensive, these have been draining resources on my end, which I no longer want to maintain.

If not mistaken, I believe all releases are now located in both Bintray and GitHub, which are also backed by Amazon S3, so most of the resources available there are duplicated or no longer relevant.

I'm sending this message as FYI and possible to gather some feedback before I continue with the removal. The following are the steps and deadlines I've in mind:

1. Today (September 3, 2018) - Backup (locally) the entire S3 buckets (`distfiles.openknapsack.org`, `packages.openknapsack.org`, `rubyinstaller`)
2. Friday (September 7, 2018) - Remove `cdn.rubyinstaller.org` CloudFront setup.
3. Monday (September 10, 2018) - Remove S3 bucket contents.

Please confirm if you have any objection with this timetable or other recommendation.

Cheers.

/cc @larsch @Azolo

**Comment by Azolo** [comment]
Looks good to me. Thanks for doing it all of these years. 💚

**Comment by dmajkic** [comment]
@luislavena - Thank you for service well done

**Comment by luislavena** [comment]
Hello folks,

Wanted to update and close this issue:

* S3 buckets were archived (in case someone needs them).
* S3 buckets were removed.
* CloudFront distribution was removed.

Closing this issue now.

Cheers.

**Comment by larskanis** [comment]
@luislavena Fortunately there are services in the meantime, which are free to use for OSS. But thank you Luis for spending these expenses for years!
