### ISSUE TITLE
Enhanced Interactive Ruby Environment

### ISSUE THREAD

**Issue by AGoh2019** [oneclick/rubyinstaller#398]
Then if the Ruby team is unwilling to develop a IDE for end-users and developers to program in.  Then, perhaps you might want to build a Enhanced Interactive Ruby Environment with all the bells and whistles of GNU Emacs, or stand-a-lone IDEs.

**Comment by larskanis** [comment]
@AGoh2019 Feel free to put your hand on something like this, but for RubyInstaller it's beyond the project scope.
