### ISSUE TITLE
Bintray sunsetting and preserving past releases

### ISSUE THREAD

**Issue by luislavena** [oneclick/rubyinstaller#400]
## What problems are you experiencing?

jFrog Bintray is sunsetting their platform: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

By May 2021, packages provided by Bintray will no longer be accessible.

In the intention to preserve the past releases and the history of this project, we should backup those installer and package probably using GitHub releases (TBC if possible).

@larskanis, opening this to coordinate the effort with you.

Thank you.

**Comment by luislavena** [comment]
(adding comments here for chronology)

I've managed to download all 2.5GB of past releases for backup purposes.

Need to research how to create past releases for each of those and upload the respective artifacts to them 😅 

Will update once I figure that out.

**Comment by MSP-Greg** [comment]
@luislavena

Thanks for thinking of this issue.  The standard GitHub Actions 'custom action' for installing Ruby just broke for Ruby 2.2 and 2.3, as it can't download the DevKit from BinTray.  Also, the OpenSSL 1.0.2 (used in Ruby 2.4) is unavailable.

Any thoughts on this issue?  I think I've got copies of what's needed, I can get the few files needed some where on GitHub, but if you have a 'master plan', let me know.

Right now, I'm mostly concerned about getting Actions CI working...

**Comment by luislavena** [comment]
Hello Greg, made a copy of all the files, was not able to find the time to
setup the releases for all of them.

My current internet bandwidth is not great, can you share the specific
versions you would like me to push first? Can do that in a few hours if
that is ok with you.

Cheers,

Sorry for to posting. Sent from mobile.

**Comment by MSP-Greg** [comment]
Luis,

Hello.  Thanks for the quick response.

I've got bandwidth, and I think I can upload the DevKit for 2.2 & 2.3 (just 64 bit) to a GitHub repo that I or @eregon have access to.  That will get Actions running as before, and give you more time to sort out what to do with the old MSYS stuff.

JFYI, the main 'action' used for loading Ruby in GitHub Actions is [ruby/setup-ruby](https://github.com/ruby/setup-ruby), which is maintained by @eregon.  Lars and I have helped with the Windows code.  I maintain [MSP-Greg/setup-ruby-pkgs](https://github.com/MSP-Greg/setup-ruby-pkgs), which uses the code from setup-ruby to install Ruby, and has additional code to make cross platform compiling (package installation, MSYS & MSYS2 issues) easier.

So, I'll see about getting Actions running, and when you have time to move the files, ping me and we can get the uri's changed?

**Comment by eregon** [comment]
There are 5 versions that setup-ruby uses:
https://github.com/ruby/setup-ruby/blob/6f2028eda533117e2ab7a1108e3bb40b01f481bc/windows-versions.js#L2-L6
It'd be great to have them available as releases & assets, similar to the newer releases.

That list of URLs is generated from
https://github.com/ruby/setup-ruby/blob/6f2028eda533117e2ab7a1108e3bb40b01f481bc/generate-windows-versions.rb
https://raw.githubusercontent.com/oneclick/rubyinstaller.org-website/master/_data/downloads.yaml
But we can also update them manually as a short-term fix.

**Comment by larskanis** [comment]
I can add all the old release files to a github release tomorrow and change the download links accordingly. I have all release files on my local hard drive. Is that OK?

**Comment by MSP-Greg** [comment]
@larskanis

That would be wonderful.  At present, Actions is only supporting 64 bit, 2.1 and later.  Missing any of the versions at BinTray uri's listed in the `windows-versions.js` file above, the DevKit for them, and I believe the following MSYS packages:
```
libffi-3.2.1
openssl-1.0.2j
ragel-6.7
sqlite-3.7.15.2
zlib-1.2.8
```

One additional item, the OpenSSL 1.0.2 Mingw64 package for Ruby 2.4.

Thanks,

Greg

**Comment by luislavena** [comment]
Hello @MSP-Greg 

>  I believe the following MSYS packages

Can you point me where those packages are being referenced? Is for building RubyInstaller itself? (I remember we custom build those packages too).

Thank you.

**Comment by MSP-Greg** [comment]
@luislavena

That list was simply the list of available packages that we wrote code for installation on Actions.  They were used for CI in extension gems that needed the packages to compile.  I believe they were at:

https://bintray.com/oneclick/OpenKnapsack

BinTray shows the packages, files, etc, but I can't download anything.

I've got openssl-1.0.2j and zlib-1.2.8 locally, and I may have more on old hard drives...

**Comment by luislavena** [comment]
Thanks @MSP-Greg, I've archived copy of OpenKnapsack up to 2015 (so misses latest openssl and libffi), and all the releases of RubyInstaller and DevKit locally (2.43GB).

It appears that this is a _brown-outs_ system maintenance of JFrog to remind users of the sunsetting:

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I'm going to create the different releases for the versions indicated and upload the Ruby binaries covered in `windows-version.js`.

Cheers.

**Comment by MSP-Greg** [comment]
> It appears that this is a brown-outs system

Cool, sort of.  I kind of recalled seeing mention of that, but...

I'm looking at my old hard drives to see what I have...

Thanks.  This is a pita, and I'm sure all of us are asking 'Maybe time to use a newer version of Ruby?', or, 'your CI passes, but no, just no.  Ruby 3.0.1 is released, and what version is EOL?'...

**Comment by luislavena** [comment]
Folks, I just pushed 2.1.9 release: https://github.com/oneclick/rubyinstaller/releases/tag/ruby-2.1.9

And doing the same for the other versions.

Cheers.

**Comment by luislavena** [comment]
@MSP-Greg @eregon the following releases have been uploaded to this repository:

* 2.1.9: https://github.com/oneclick/rubyinstaller/releases/tag/ruby-2.1.9
* 2.2.6: https://github.com/oneclick/rubyinstaller/releases/tag/ruby-2.2.6
* 2.3.0: https://github.com/oneclick/rubyinstaller/releases/tag/ruby-2.3.0
* 2.3.1: https://github.com/oneclick/rubyinstaller/releases/tag/ruby-2.3.1
* 2.3.3: https://github.com/oneclick/rubyinstaller/releases/tag/ruby-2.3.3

It is now possible to replace the URLs for the ones from GitHub.

@MSP-Greg I will deal with OpenKnapsack once BinTray service window is over, in the meantime, can you confirm if the following DevKit versions are the ones you need?

* `DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe`
* `DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe`

(as I understand, we only care about the 64bits version, but wanted to confirm).

Thank you.

**Comment by luislavena** [comment]
@MSP-Greg @eregon I've pushed DevKit 4.7.2, which I believe was the one referenced in `windows-version.js` document:

https://github.com/oneclick/rubyinstaller/releases/tag/devkit-4.7.2

re: OpenKnapsack packages, I just scanned by local backup and didn't have those, so will wait for JFrog to confirm they are done with their brown-out tests and then perform a full backup of these too 🤞🏽 

Let me know if those packages are good and if the CI environments are restored.

Cheers.

**Comment by eregon** [comment]
CI passes now on Windows for ruby/setup-ruby (https://github.com/ruby/setup-ruby/pull/172), thank you all!

**Comment by larskanis** [comment]
Thank you @luislavena  for adding the releases to oneclick/rubyinstaller !  Is there any need to add all past releases? If not, I would like to keep it how it is.

**Comment by luislavena** [comment]
@larskanis I think we are good with just the latest releases of those versions. 

Now that I've back at home and have a faster internet connection might be able to spend a few hours uploading the oldest releases (for historical purposes).

I'm about to upload the Knapsack packages to the archived repository: https://github.com/oneclick/knapsack-recipes, so anyone wanting to rebuild any of the old version of Ruby can still do it. (not sure why they would want that anyway 😁)

Cheers.

**Comment by MSP-Greg** [comment]
@luislavena

Thanks for your work on this.  I grabbed some of them, since some extension gems need the old packages to compile.

I'll switch the links over to the oneclick repo when you're finished...

**Comment by luislavena** [comment]
Hello @MSP-Greg, I've pushed several of the packages you mentioned [in previous comment](https://github.com/oneclick/rubyinstaller/issues/400#issuecomment-827038328)

* [libffi-3.2.1](https://github.com/oneclick/knapsack-recipes/releases/tag/libffi-3.2.1)
* [openssl-1.0.2j](https://github.com/oneclick/knapsack-recipes/releases/tag/openssl-1.0.2j)
* [ragel-6.7](https://github.com/oneclick/knapsack-recipes/releases/tag/ragel-6.7)
* [sqlite-3.7.15.2](https://github.com/oneclick/knapsack-recipes/releases/tag/sqlite-3.7.15.2)
* [zlib-1.2.8](https://github.com/oneclick/knapsack-recipes/releases/tag/zlib-1.2.8)

Plus a few others that I saw in the git log and started to tag 😅 

I might be missing the `distfiles` for some of those, so will not archive the project yet until those entries are covered too.

Let me know if the above resources work for you before I continue.

Cheers.

**Comment by MSP-Greg** [comment]
Luis,

Thanks.  What you've listed is what I had previously, and no one has asked for additional packages.

Currently, I moved the following to GitHub.  Note that GitHub Actions currently only supports 64 bit.  Also, I've never seen mention of people wanting to recompile older Ruby versions.  So the packages were just for extension gems...

```
gdbm-1.8.3
libffi-3.2.1
libiconv-1.14
libyaml-0.1.7
openssl-1.0.2j
ragel-6.7
sqlite-3.7.15.2
zlib-1.2.8
```

**Comment by luislavena** [comment]
Excellent @MSP-Greg, let me add back gdbm-1.8.3 and  libiconv-1.14 and we should be good.

**Comment by luislavena** [comment]
@MSP-Greg done:

* [gdbm-1.8.3](https://github.com/oneclick/knapsack-recipes/releases/tag/gdbm-1.8.3)
* [libiconv-1.14](https://github.com/oneclick/knapsack-recipes/releases/tag/libiconv-1.14)

I've pushed the x86 versions since I had the backup files, but highly unlikely someone is installing or using the 32bits version of those or Ruby anyway.

@larskanis: will take a look over the weekend to upload past versions out of BinTray and update the website links so those are not broken.

Cheers.

**Comment by MSP-Greg** [comment]
@larskanis

Do you have a copy of mingw-w64-i686-openssl-1.0.2.u-1-any.pkg.tar.zst and the sig file?  Or, is it online somewhere?

**Comment by larskanis** [comment]
@MSP-Greg I uploaded the two files to https://github.com/oneclick/rubyinstaller/releases/tag/head

@luislavena I have a half finished script to upload all release files. May I finish it and do the uploads?

**Comment by luislavena** [comment]
Hello @larskanis, does the script creates separate releases or drops everything in a single "legacy" one? Was thinking there were too many releases to go and create tags for, so perhaps an archive/legacy one and all the files there should be enough.

What do you think?

Feel free to email me so we can make sure all the past releases can get uploaded, or I can run it from my copy, just let me know.

Thank you.

**Comment by larskanis** [comment]
@luislavena I would create distinct releases the same as you started. Tagging to the right commit is difficult, so that I would use one common commit. But I'm also OK with one legacy release.

**Comment by luislavena** [comment]
@larskanis I think one common commit and individual releases are perfect, just don't invest lot of time on it (there are better thing to do, hehe).

Once again thank you for taking the time on this.
❤️❤️❤️

**Comment by larskanis** [comment]
All past release files are uploaded to github now and the download links on https://rubyinstaller.org/downloads/archives/ are updated. See commit https://github.com/oneclick/rubyinstaller.org-website/commit/3231d33308566898db5952fb8a463193dee9f258
